--------------------------------------------------------
--  DDL for Table STUDENT_CERTIFICATE
--------------------------------------------------------

CREATE TABLE STUDENT_CERTIFICATE
(	STUDENT_CERTIFICATE_ID RAW(16),
     CERTIFICATE CLOB,
     CERTIFICATE_TYPE_CODE VARCHAR2(20 BYTE),
     GRADUTION_STUDENT_RECORD_ID RAW(16),
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP,
     CONSTRAINT STUDENT_CERTIFICATE_ID_PK PRIMARY KEY (STUDENT_CERTIFICATE_ID)
         USING INDEX TABLESPACE API_GRAD_DATA  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE API_GRAD_DATA NO INMEMORY
    LOB (CERTIFICATE) STORE AS SECUREFILE (
    TABLESPACE API_GRAD_BLOB_DATA ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;

alter table STUDENT_CERTIFICATE
    add constraint STUDENT_CERTIFICATE_CODE_FK2 foreign key(CERTIFICATE_TYPE_CODE)
        references CERTIFICATE_TYPE_CODE(CERTIFICATE_TYPE_CODE);
