--------------------------------------------------------
--  DDL for Table SIGNATURE_BLOCK_CODE
--------------------------------------------------------

  CREATE TABLE "SIGNATURE_BLOCK_CODE" 
   (	"SIGNATURE_BLOCK_CODE" VARCHAR2(10 BYTE), 
	"LABEL" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CREATE_USER" VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE, 
	"CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE, 
	"UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "SIGNATURE_BLOCK_CODE_PK" PRIMARY KEY ("SIGNATURE_BLOCK_CODE")
	 USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE   
	NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;

