--------------------------------------------------------
--  DDL for Table STUDENT_REPORT
--------------------------------------------------------

GRANT SELECT ON CERTIFICATE_TYPE_CODE TO GRAD_READONLY;
GRANT SELECT ON TRANSCRIPT_TYPE_CODE TO GRAD_READONLY;
GRANT SELECT ON SIGNATURE_BLOCK_TYPE TO GRAD_READONLY;
GRANT SELECT ON PROGRAM_CERTIFICATE_TRANSCRIPT TO GRAD_READONLY;
GRANT SELECT ON DIGIT_SIGNATURE TO GRAD_READONLY;
GRANT SELECT ON REPORT_TYPE_CODE TO GRAD_READONLY;
GRANT SELECT ON DOCUMENT_STATUS_CODE TO GRAD_READONLY;
GRANT SELECT ON STUDENT_CERTIFICATE TO GRAD_READONLY;
GRANT SELECT ON STUDENT_REPORT TO GRAD_READONLY;
