--------------------------------------------------------
--  DDL for Table DIGIT_SIGNATURE_TYPE_CODE
--------------------------------------------------------


  CREATE TABLE "DIGIT_SIGNATURE_TYPE_CODE" 
   (	"SIGNATURE_BLOCK_TYPE" VARCHAR2(3 BYTE), 
	"SIGNATURE_BLOCK" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CREATE_USER" VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE, 
	"CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATE_USER" VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE, 
	"UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "DIGIT_SIGNATURE_TYPE_CODE_PK" PRIMARY KEY ("SIGNATURE_BLOCK_TYPE")
	 USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;
