--------------------------------------------------------
--  DDL for Table DIGIT_SIGNATURE
--------------------------------------------------------

CREATE TABLE DIGIT_SIGNATURE
(	"DIGIT_SIGNATURE_ID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
     "DIGIT_SIGNATURE_BLOB" BLOB,
     "DIGIT_SIGNATURE_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "DIGIT_SIGNATURE_NAME" VARCHAR2(64 BYTE),
     "CREATE_USER" VARCHAR2(30 BYTE) DEFAULT USER,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP,
     "UPDATE_USER" VARCHAR2(30 BYTE) DEFAULT USER,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP,
     CONSTRAINT DIGIT_SIGNATURE_TYPE_ID_PK PRIMARY KEY (DIGIT_SIGNATURE_ID)
         USING INDEX TABLESPACE API_GRAD_IDX  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE API_GRAD_DATA NO INMEMORY
    LOB (DIGIT_SIGNATURE_BLOB) STORE AS SECUREFILE (
    TABLESPACE API_GRAD_BLOB_DATA ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;

