--------------------------------------------------------
--  File created - Wednesday-August-04-2021
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GRAD_REPORT_SIGNATURE
--------------------------------------------------------

CREATE TABLE "DIGIT_SIGNATURE"
(	"DIGIT_SIGNATURE_ID" RAW(16) DEFAULT SYS_GUID(),
     "DIGIT_SIGNATURE_TITLE" VARCHAR2(64 BYTE) NOT NULL ENABLE,
     "DIGIT_SIGNATURE_BLOB" BLOB,
     "DIGIT_SIGNATURE_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "DIGIT_SIGNATURE_NAME" VARCHAR2(64 BYTE),
     "DISTNO" VARCHAR2(3 BYTE),
     "DIST_NAME" VARCHAR2(64 BYTE),
     "EFFECTIVE_DATE" DATE NOT NULL ENABLE,
     "EXPIRY_DATE" DATE,
     "CREATE_USER" VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT DIGIT_SIGNATURE_TYPE_ID_PK PRIMARY KEY (DIGIT_SIGNATURE_ID)
         USING INDEX TABLESPACE API_GRAD_IDX  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY
    LOB ("DIGIT_SIGNATURE_BLOB") STORE AS SECUREFILE (
    TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;

