--------------------------------------------------------
--  File created - Wednesday-August-04-2021
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROGRAM_CERTIFICATE_TRANSCRIPT
--------------------------------------------------------

CREATE TABLE PROGRAM_CERTIFICATE_TRANSCRIPT
(	PROGRAM_CERT_TRANS_ID RAW(20) DEFAULT SYS_GUID() NOT NULL ENABLE,
     GRADUATION_PROGRAM_CODE VARCHAR2(8 BYTE) NOT NULL ENABLE,
     SCHOOL_CATEGORY_CODE VARCHAR2(3 BYTE),
     CERTIFICATE_TYPE_CODE VARCHAR2(3 BYTE),
     TRANSCRIPT_TYPE_CODE VARCHAR2(10 BYTE),
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP,
     CONSTRAINT PROGRAM_CERT_TRANS_PK PRIMARY KEY (PROGRAM_CERT_TRANS_ID)
         USING INDEX TABLESPACE API_GRAD_IDX  ENABLE,
     CONSTRAINT CERTIFICATE_TYPE_CODE_FK1 FOREIGN KEY (CERTIFICATE_TYPE_CODE)
         REFERENCES CERTIFICATE_TYPE_CODE (CERTIFICATE_TYPE_CODE) ENABLE,
     CONSTRAINT TRANSCRIPT_TYPE_CODE_FK2 FOREIGN KEY (TRANSCRIPT_TYPE_CODE)
         REFERENCES TRANSCRIPT_TYPE_CODE (TRANSCRIPT_TYPE_CODE) ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING TABLESPACE API_GRAD_DATA   NO INMEMORY ;

