--------------------------------------------------------
--  File created - Wednesday-August-04-2021
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GRAD_REPORT_SIGNATURE
--------------------------------------------------------

CREATE TABLE "GRAD_REPORT_SIGNATURE"
(	"GRAD_REPORT_SIGNATURE_ID" RAW(16) DEFAULT SYS_GUID(),
     "GRAD_REPORT_SIGNATURE" BLOB,
     "GRAD_REPORT_SIGNATURE_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "CREATE_USER" VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT GRAD_REPORT_SIGNATURE_ID_PK PRIMARY KEY (GRAD_REPORT_SIGNATURE_ID)
         USING INDEX TABLESPACE API_GRAD_IDX  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY
    LOB ("GRAD_REPORT_SIGNATURE") STORE AS SECUREFILE (
    TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;

--------------------------------------------------------
--  DDL for Index GRAD_REPORT_SIGNATURE_CODE_UQ
--------------------------------------------------------

CREATE UNIQUE INDEX "GRAD_REPORT_SIGNATURE_CODE_UK" ON "GRAD_REPORT_SIGNATURE" ("GRAD_REPORT_SIGNATURE_CODE")
    TABLESPACE "API_GRAD_IDX" ;

