--------------------------------------------------------
--  File created - Wednesday-August-04-2021
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CERTIFICATE_TYPE_CODE
--------------------------------------------------------

CREATE TABLE CERTIFICATE_TYPE_CODE
(	CERTIFICATE_TYPE_CODE VARCHAR2(3 BYTE),
     LABEL VARCHAR2(50 BYTE),
     DESCRIPTION VARCHAR2(255 BYTE),
     DISPLAY_ORDER NUMBER,
     EFFECTIVE_DATE DATE,
     EXPIRY_DATE DATE,
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP,
     CONSTRAINT CERTIFICATE_TYPE_CODE_PK PRIMARY KEY (CERTIFICATE_TYPE_CODE)
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
             STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
             PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
             BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
             TABLESPACE API_GRAD_IDX  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY ;