--------------------------------------------------------
--  File created - Wednesday-August-04-2021
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GRAD_REPORT_SIGNATURE
--------------------------------------------------------

CREATE TABLE "GRAD_REPORT_SIGNATURE"
(	"GRAD_REPORT_SIGNATURE_ID" RAW(16) DEFAULT SYS_GUID(),
     "GRAD_REPORT_SIGNATURE" BLOB,
     "GRAD_REPORT_SIGNATURE_CODE" VARCHAR2(20 BYTE),
     "CREATE_USER" VARCHAR2(30 BYTE) DEFAULT USER,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP,
     "UPDATE_USER" VARCHAR2(30 BYTE) DEFAULT USER,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY
    LOB ("GRAD_REPORT_SIGNATURE") STORE AS SECUREFILE (
    TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;
--------------------------------------------------------
--  DDL for Index GRAD_REPORT_SIGNATURE_ID_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "GRAD_REPORT_SIGNATURE_ID_PK" ON "GRAD_REPORT_SIGNATURE" ("GRAD_REPORT_SIGNATURE_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "API_GRAD_IDX" ;
--------------------------------------------------------
--  DDL for Index GRAD_REPORT_SIGNATURE_CODE_UQ
--------------------------------------------------------

CREATE UNIQUE INDEX "GRAD_REPORT_SIGNATURE_CODE_UQ" ON "GRAD_REPORT_SIGNATURE" ("GRAD_REPORT_SIGNATURE_CODE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "API_GRAD_IDX" ;
--------------------------------------------------------
--  Constraints for Table GRAD_REPORT_SIGNATURE
--------------------------------------------------------

ALTER TABLE "GRAD_REPORT_SIGNATURE" ADD CONSTRAINT "GRAD_REPORT_SIGNATURE_ID_PK" PRIMARY KEY ("GRAD_REPORT_SIGNATURE_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
        BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "API_GRAD_IDX"  ENABLE;
