UPDATE CERTIFICATE_TYPE_CODE arc SET arc.EXPIRY_DATE = NULL WHERE arc.EXPIRY_DATE = TO_DATE('2099-12-31', 'yyyy-mm-dd');
UPDATE DOCUMENT_STATUS_CODE arc SET arc.EXPIRY_DATE = NULL WHERE arc.EXPIRY_DATE = TO_DATE('2099-12-31', 'yyyy-mm-dd');
UPDATE REPORT_TYPE_CODE arc SET arc.EXPIRY_DATE = NULL WHERE arc.EXPIRY_DATE = TO_DATE('2099-12-31', 'yyyy-mm-dd');
UPDATE SCHOOL_FUNDING_GROUP_CODE arc SET arc.EXPIRY_DATE = NULL WHERE arc.EXPIRY_DATE = TO_DATE('2099-12-31', 'yyyy-mm-dd');