--------------------------------------------------------
--  DDL for Table SCHOOL_FUNDING_GROUP_CODE
--------------------------------------------------------

CREATE TABLE SCHOOL_FUNDING_GROUP_CODE
(	SCHOOL_FUNDING_GROUP_CODE VARCHAR2(1 BYTE),
     LABEL VARCHAR2(50 BYTE),
     DESCRIPTION VARCHAR2(255 BYTE),
     DISPLAY_ORDER NUMBER,
     EFFECTIVE_DATE DATE,
     EXPIRY_DATE DATE,
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY ;
--------------------------------------------------------
--  DDL for Index SCHOOL_FUNDING_GROUP_CODE_PK
--------------------------------------------------------

CREATE UNIQUE INDEX SCHOOL_FUNDING_GROUP_CODE_PK ON SCHOOL_FUNDING_GROUP_CODE (SCHOOL_FUNDING_GROUP_CODE)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE API_GRAD_DATA ;
--------------------------------------------------------
--  Constraints for Table SCHOOL_FUNDING_GROUP_CODE
--------------------------------------------------------

ALTER TABLE SCHOOL_FUNDING_GROUP_CODE MODIFY (SCHOOL_FUNDING_GROUP_CODE NOT NULL ENABLE);
ALTER TABLE SCHOOL_FUNDING_GROUP_CODE ADD CONSTRAINT SCHOOL_FUNDING_GROUP_CODE_PK PRIMARY KEY (SCHOOL_FUNDING_GROUP_CODE)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
        BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE API_GRAD_DATA  ENABLE;
