--------------------------------------------------------
--  File created - Wednesday-August-04-2021
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CERTIFICATE_TYPE_CODE
--------------------------------------------------------

CREATE TABLE DIGIT_SIGNATURE_TYPE_CODE
(	DIGIT_SIGNATURE_TYPE_CODE VARCHAR2(3 BYTE),
     LABEL VARCHAR2(50 BYTE) NOT NULL ENABLE,
     DESCRIPTION VARCHAR2(255 BYTE) NOT NULL ENABLE,
     DISPLAY_ORDER NUMBER NOT NULL ENABLE,
     EFFECTIVE_DATE DATE NOT NULL ENABLE,
     EXPIRY_DATE DATE,
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT DIGIT_SIGNATURE_TYPE_CODE_PK PRIMARY KEY (DIGIT_SIGNATURE_TYPE_CODE)
         USING INDEX TABLESPACE API_GRAD_IDX  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY ;