--------------------------------------------------------
--  DDL for Table STUDENT_CERTIFICATE
--------------------------------------------------------

CREATE TABLE STUDENT_CERTIFICATE
(	STUDENT_CERTIFICATE_ID RAW(16),
     CERTIFICATE CLOB,
     CERTIFICATE_TYPE_CODE VARCHAR2(20 BYTE),
     GRADUTION_STUDENT_RECORD_ID RAW(16),
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY
    LOB (CERTIFICATE) STORE AS SECUREFILE (
    TABLESPACE API_GRAD_BLOB_DATA ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;
--------------------------------------------------------
--  DDL for Index STUDENT_CERTIFICATE_ID_PK
--------------------------------------------------------

CREATE UNIQUE INDEX STUDENT_CERTIFICATE_ID_PK ON STUDENT_CERTIFICATE (STUDENT_CERTIFICATE_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE API_GRAD_BLOB_DATA ;
--------------------------------------------------------
--  Constraints for Table STUDENT_CERTIFICATE
--------------------------------------------------------

ALTER TABLE STUDENT_CERTIFICATE ADD CONSTRAINT STUDENT_CERTIFICATE_ID_PK PRIMARY KEY (STUDENT_CERTIFICATE_ID)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
        BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE API_GRAD_BLOB_DATA  ENABLE;
