--------------------------------------------------------
--  DDL for Table STUDENT_REPORT
--------------------------------------------------------

CREATE TABLE STUDENT_REPORT
(	STUDENT_REPORT_ID RAW(16),
     GRADUTION_STUDENT_RECORD_ID RAW(16),
     REPORT CLOB,
     REPORT_TYPE_CODE VARCHAR2(10 BYTE),
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY
    LOB (REPORT) STORE AS SECUREFILE (
    TABLESPACE API_GRAD_BLOB_DATA ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;
--------------------------------------------------------
--  DDL for Index STUDENT_REPORT_PK
--------------------------------------------------------

CREATE UNIQUE INDEX STUDENT_REPORT_PK ON STUDENT_REPORT (STUDENT_REPORT_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE API_GRAD_BLOB_DATA ;
--------------------------------------------------------
--  Constraints for Table STUDENT_REPORT
--------------------------------------------------------

ALTER TABLE STUDENT_REPORT ADD CONSTRAINT STUDENT_REPORT_PK PRIMARY KEY (STUDENT_REPORT_ID)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
        BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE API_GRAD_BLOB_DATA  ENABLE;
