--------------------------------------------------------
--  File created - Wednesday-August-04-2021
--------------------------------------------------------
--------------------------------------------------------
--  DML for Table CERTIFICATE_TYPE_CODE
--------------------------------------------------------

INSERT INTO DIGIT_SIGNATURE_TYPE_CODE (DIGIT_SIGNATURE_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) VALUES ('MOE','MOE','Minister of Education',10,SYSDATE,TIMESTAMP'2099-12-31 00:00:00.0',DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO DIGIT_SIGNATURE_TYPE_CODE (DIGIT_SIGNATURE_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) VALUES ('MOAE','MOAE','Minister of Advanced Education',20,SYSDATE,TIMESTAMP'2099-12-31 00:00:00.0',DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO DIGIT_SIGNATURE_TYPE_CODE (DIGIT_SIGNATURE_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) VALUES ('MOE_DM','MOE_DM','Deputy Minister of Education',30,SYSDATE,TIMESTAMP'2099-12-31 00:00:00.0',DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO DIGIT_SIGNATURE_TYPE_CODE (DIGIT_SIGNATURE_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) VALUES ('MOE_ADM','MOE_ADM','Assistant Deputy Minister',40,SYSDATE,TIMESTAMP'2099-12-31 00:00:00.0',DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO DIGIT_SIGNATURE_TYPE_CODE (DIGIT_SIGNATURE_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) VALUES ('103','103','Offshore',50,SYSDATE,TIMESTAMP'2099-12-31 00:00:00.0',DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO DIGIT_SIGNATURE_TYPE_CODE (DIGIT_SIGNATURE_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) VALUES ('999','999','Inspector of Independent Schools',60,SYSDATE,TIMESTAMP'2099-12-31 00:00:00.0',DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO DIGIT_SIGNATURE_TYPE_CODE (DIGIT_SIGNATURE_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) VALUES ('MOEF','MOEF','Ministre de l''Éducation',70,SYSDATE,TIMESTAMP'2099-12-31 00:00:00.0',DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO DIGIT_SIGNATURE_TYPE_CODE (DIGIT_SIGNATURE_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) VALUES ('DISTRICT','DISTRICT','Superintendent of Schools',80,SYSDATE,TIMESTAMP'2099-12-31 00:00:00.0',DEFAULT,DEFAULT,DEFAULT,DEFAULT);
INSERT INTO DIGIT_SIGNATURE_TYPE_CODE (DIGIT_SIGNATURE_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE,CREATE_USER,CREATE_DATE,UPDATE_USER,UPDATE_DATE) VALUES ('DISTRICTF','DISTRICTF','Direction générale de la commission scolaire',90,SYSDATE,TIMESTAMP'2099-12-31 00:00:00.0',DEFAULT,DEFAULT,DEFAULT,DEFAULT);
