--------------------------------------------------------
--  DDL for Table DIGITALAL_SIGNATURE
--------------------------------------------------------

CREATE TABLE DIGITAL_SIGNATURE
(	"DIGITAL_SIGNATURE_KEY" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
     "DIGITAL_SIGNATURE_BLOB" BLOB,
     "DIGITAL_SIGNATURE_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
     "DIGITAL_SIGNATURE_NAME" VARCHAR2(64 BYTE),
     "CREATE_USER" VARCHAR2(30 BYTE) DEFAULT USER,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP,
     "UPDATE_USER" VARCHAR2(30 BYTE) DEFAULT USER,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP,
     CONSTRAINT DIGITAL_SIGNATURE_TYPE_ID_PK PRIMARY KEY (DIGITAL_SIGNATURE_KEY)
         USING INDEX TABLESPACE API_GRAD_IDX  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE API_GRAD_DATA NO INMEMORY
    LOB (DIGITAL_SIGNATURE_BLOB) STORE AS SECUREFILE (
    TABLESPACE API_GRAD_BLOB_DATA ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;

