--------------------------------------------------------
--  DDL for Table STUDENT_REPORT
--------------------------------------------------------

GRANT SELECT ON CERTIFICATE_TYPE_CODE TO GRAD_READONLY;
GRANT SELECT ON DOCUMENT_STATUS_CODE TO GRAD_READONLY;
GRANT SELECT ON GRAD_REPORT_SIGNATURE TO GRAD_READONLY;
GRANT SELECT ON REPORT_TYPE_CODE TO GRAD_READONLY;
GRANT SELECT ON SCHOOL_FUNDING_GROUP_CODE TO GRAD_READONLY;
GRANT SELECT ON PROGRAM_CERTIFICATE TO GRAD_READONLY;
GRANT SELECT ON STUDENT_CERTIFICATE TO GRAD_READONLY;
GRANT SELECT ON STUDENT_REPORT TO GRAD_READONLY;
