--------------------------------------------------------
--  File created - Tuesday-August-10-2021
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROGRAM_CERTIFICATE
--------------------------------------------------------

CREATE TABLE PROGRAM_CERTIFICATE
(	PROGRAM_CERTIFICATE_ID RAW(20) DEFAULT SYS_GUID(),
     PROGRAM_CODE VARCHAR2(8 BYTE),
     SCHOOL_FUNDING_GROUP_CODE VARCHAR2(1 BYTE),
     CERTIFICATE_TYPE_CODE VARCHAR2(3 BYTE),
     BC_MAIL_MEDIA_CODE VARCHAR2(4 BYTE),
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY ;
--------------------------------------------------------
--  DDL for Index PROGRAM_CERTIFICATE_PK
--------------------------------------------------------

CREATE UNIQUE INDEX PROGRAM_CERTIFICATE_PK ON PROGRAM_CERTIFICATE (PROGRAM_CERTIFICATE_ID)
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE API_GRAD_DATA ;
--------------------------------------------------------
--  Constraints for Table PROGRAM_CERTIFICATE
--------------------------------------------------------

ALTER TABLE PROGRAM_CERTIFICATE MODIFY (PROGRAM_CERTIFICATE_ID NOT NULL ENABLE);
ALTER TABLE PROGRAM_CERTIFICATE ADD CONSTRAINT PROGRAM_CERTIFICATE_PK PRIMARY KEY (PROGRAM_CERTIFICATE_ID)
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
        BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE API_GRAD_DATA  ENABLE;
