--------------------------------------------------------
--  DDL for Table STUDENT_REPORT
--------------------------------------------------------

CREATE TABLE STUDENT_REPORT
(	STUDENT_REPORT_ID RAW(16),
     GRADUTION_STUDENT_RECORD_ID RAW(16),
     REPORT CLOB,
     REPORT_TYPE_CODE VARCHAR2(10 BYTE),
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP,
     CONSTRAINT STUDENT_REPORT_PK PRIMARY KEY (STUDENT_REPORT_ID)
         USING INDEX TABLESPACE API_GRAD_DATA  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE API_GRAD_DATA NO INMEMORY
    LOB (REPORT) STORE AS SECUREFILE (
    TABLESPACE API_GRAD_BLOB_DATA ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;

alter table STUDENT_REPORT
    add constraint STUD_REPORT_REPORT_TYPE_CD_FK foreign key(REPORT_TYPE_CODE)
        references REPORT_TYPE_CODE(REPORT_TYPE_CODE);

