--------------------------------------------------------
--  File created - Tuesday-August-10-2021
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROGRAM_CERTIFICATE
--------------------------------------------------------

CREATE TABLE PROGRAM_CERTIFICATE
(	PROGRAM_CERTIFICATE_ID RAW(20) DEFAULT SYS_GUID() NOT NULL,
     PROGRAM_CODE VARCHAR2(8 BYTE),
     SCHOOL_FUNDING_GROUP_CODE VARCHAR2(1 BYTE),
     CERTIFICATE_TYPE_CODE VARCHAR2(3 BYTE),
     BC_MAIL_MEDIA_CODE VARCHAR2(4 BYTE),
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP,
     CONSTRAINT PROGRAM_CERTIFICATE_PK PRIMARY KEY (PROGRAM_CERTIFICATE_ID)
         USING INDEX TABLESPACE API_GRAD_DATA  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY ;

alter table PROGRAM_CERTIFICATE
    add constraint STUDENT_CERTIFICATE_CODE_FK1 foreign key(CERTIFICATE_TYPE_CODE)
        references CERTIFICATE_TYPE_CODE(CERTIFICATE_TYPE_CODE);