--------------------------------------------------------
--  DDL for Table SCHOOL_FUNDING_GROUP_CODE
--------------------------------------------------------

CREATE TABLE SCHOOL_FUNDING_GROUP_CODE
(	SCHOOL_FUNDING_GROUP_CODE VARCHAR2(1 BYTE) NOT NULL,
     LABEL VARCHAR2(50 BYTE),
     DESCRIPTION VARCHAR2(255 BYTE),
     DISPLAY_ORDER NUMBER,
     EFFECTIVE_DATE DATE,
     EXPIRY_DATE DATE,
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP,
     CONSTRAINT SCHOOL_FUNDING_GROUP_CODE_PK PRIMARY KEY (SCHOOL_FUNDING_GROUP_CODE)
         USING INDEX TABLESPACE API_GRAD_DATA  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE "API_GRAD_DATA" NO INMEMORY ;
