--------------------------------------------------------
--  DDL for Table STUDENT_CERTIFICATE
--------------------------------------------------------

CREATE TABLE STUDENT_CERTIFICATE
(	STUDENT_CERTIFICATE_ID RAW(16) DEFAULT SYS_GUID(),
     CERTIFICATE CLOB,
     CERTIFICATE_TYPE_CODE VARCHAR2(10 BYTE) NOT NULL ENABLE,
     GRADUTION_STUDENT_RECORD_ID RAW(16) NOT NULL ENABLE,
     DOCUMENT_STATUS_CODE VARCHAR2(5 BYTE),
     DISTRIBUTION_DATE DATE,
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT STUDENT_CERTIFICATE_ID_PK PRIMARY KEY (STUDENT_CERTIFICATE_ID)
         USING INDEX TABLESPACE API_GRAD_IDX  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE API_GRAD_DATA NO INMEMORY
    LOB (CERTIFICATE) STORE AS SECUREFILE (
    TABLESPACE API_GRAD_BLOB_DATA ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;

alter table STUDENT_CERTIFICATE
    add constraint STUD_CERT_CERT_TYPE_CD_FK foreign key(CERTIFICATE_TYPE_CODE)
        references CERTIFICATE_TYPE_CODE(CERTIFICATE_TYPE_CODE);

