DELETE FROM REPORT_TYPE_CODE WHERE REPORT_TYPE_CODE='XML';
DELETE FROM REPORT_TYPE_CODE WHERE REPORT_TYPE_CODE='TRANIP';
DELETE FROM REPORT_TYPE_CODE WHERE REPORT_TYPE_CODE='CERT';
DELETE FROM REPORT_TYPE_CODE WHERE REPORT_TYPE_CODE='TRAN';
