UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Scott Robinson' WHERE DIGITAL_SIGNATURE_CODE='038';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Stephen McNiven' WHERE DIGITAL_SIGNATURE_CODE='058';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Scott Saywell' WHERE DIGITAL_SIGNATURE_CODE='068';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Diana Samchuck' WHERE DIGITAL_SIGNATURE_CODE='081';
