UPDATE PROGRAM_CERTIFICATE_TRANSCRIPT SET SCHOOL_CATEGORY_CODE='' WHERE GRADUATION_PROGRAM_CODE='FI' AND CERTIFICATE_TYPE_CODE='F';

DELETE FROM PROGRAM_CERTIFICATE_TRANSCRIPT WHERE GRADUATION_PROGRAM_CODE = 'FI' AND CERTIFICATE_TYPE_CODE ='FIND';