UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Sean Nosek' WHERE DIGITAL_SIGNATURE_CODE='034';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Christopher Usih' WHERE DIGITAL_SIGNATURE_CODE='038';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Dr. Jeremy Morrow' WHERE DIGITAL_SIGNATURE_CODE='071';