-- F
UPDATE CERTIFICATE_TYPE_CODE SET LANGUAGE = 'French' , LABEL = 'diplôme (French Immersion)'
WHERE CERTIFICATE_TYPE_CODE = 'F';
-- E
UPDATE CERTIFICATE_TYPE_CODE SET LANGUAGE = 'English' , LABEL = 'Dogwood (Public)'
WHERE CERTIFICATE_TYPE_CODE = 'E';
-- EI
UPDATE CERTIFICATE_TYPE_CODE SET LANGUAGE = 'English' , LABEL = 'Dogwood (Independent)'
WHERE CERTIFICATE_TYPE_CODE = 'EI';
-- S
UPDATE CERTIFICATE_TYPE_CODE SET LANGUAGE = 'French' , LABEL = 'diplôme (Programme francophone)'
WHERE CERTIFICATE_TYPE_CODE = 'S';
-- A
UPDATE CERTIFICATE_TYPE_CODE SET LANGUAGE = 'English' , LABEL = 'Adult Dogwood (Public)'
WHERE CERTIFICATE_TYPE_CODE = 'A';
-- AI
UPDATE CERTIFICATE_TYPE_CODE SET LANGUAGE = 'English' , LABEL = 'Adult Dogwood (Independent)'
WHERE CERTIFICATE_TYPE_CODE = 'AI';
-- SC
UPDATE CERTIFICATE_TYPE_CODE SET LANGUAGE = 'English' , LABEL = 'Evergreen'
WHERE CERTIFICATE_TYPE_CODE = 'SC';
-- O
UPDATE CERTIFICATE_TYPE_CODE SET LANGUAGE = 'English' , LABEL = 'Dogwood (Offshore)'
WHERE CERTIFICATE_TYPE_CODE = 'O';
-- SCF
UPDATE CERTIFICATE_TYPE_CODE SET LANGUAGE = 'French' , LABEL = 'Evergreen (Programme francophone)'
WHERE CERTIFICATE_TYPE_CODE = 'SCF';
