UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Viveka Johnson' WHERE DIGITAL_SIGNATURE_CODE='005';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Roberta Kubik' WHERE DIGITAL_SIGNATURE_CODE='019';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Tim Davie' WHERE DIGITAL_SIGNATURE_CODE='070';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Angus Wilson' WHERE DIGITAL_SIGNATURE_CODE='075';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Aaron Callaghan' WHERE DIGITAL_SIGNATURE_CODE='082';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Bertrand Dupain' WHERE DIGITAL_SIGNATURE_CODE='093';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Selina Robinson' WHERE DIGITAL_SIGNATURE_CODE='MOAE';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Rachna Singh' WHERE DIGITAL_SIGNATURE_CODE='MOE';