UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Steve Wyer', UPDATE_USER = 'GRAD_REPORT_API', UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='006';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Teresa Downs', UPDATE_USER = 'GRAD_REPORT_API', UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='042';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Jameel Aziz', UPDATE_USER = 'GRAD_REPORT_API', UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='057';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Vessy Mochikas', UPDATE_USER = 'GRAD_REPORT_API', UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='074';
