--------------------------------------------------------
--  DDL for Table DISTRICT_REPORT
--------------------------------------------------------

CREATE TABLE DISTRICT_REPORT
(	 DISTRICT_REPORT_ID RAW(16) DEFAULT SYS_GUID(),
     REPORT CLOB,
     REPORT_TYPE_CODE VARCHAR2(20 BYTE) NOT NULL ENABLE,
     DISTRICT_ID RAW(16) NOT NULL ENABLE,
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER NOT NULL ENABLE,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT DISTRICT_REPORT_ID_PK PRIMARY KEY (DISTRICT_REPORT_ID)
         USING INDEX TABLESPACE API_GRAD_IDX  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE API_GRAD_DATA NO INMEMORY
    LOB (REPORT) STORE AS SECUREFILE (
    TABLESPACE API_GRAD_BLOB_DATA ENABLE STORAGE IN ROW
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES) ;

alter table DISTRICT_REPORT
    add constraint DIS_REP_TYPE_CD_FK foreign key(REPORT_TYPE_CODE)
        references REPORT_TYPE_CODE(REPORT_TYPE_CODE);