-- E
UPDATE CERTIFICATE_TYPE_CODE SET DESCRIPTION = 'B.C. Certificate of Graduation - Public School'
WHERE CERTIFICATE_TYPE_CODE = 'E';
-- EI
UPDATE CERTIFICATE_TYPE_CODE SET DESCRIPTION = 'B.C. Certificate of Graduation - Independent School'
WHERE CERTIFICATE_TYPE_CODE = 'EI';
-- A
UPDATE CERTIFICATE_TYPE_CODE SET DESCRIPTION = 'Adult Graduation Diploma - Public School'
WHERE CERTIFICATE_TYPE_CODE = 'A';
-- AI
UPDATE CERTIFICATE_TYPE_CODE SET DESCRIPTION = 'Adult Graduation Diploma - Independent School'
WHERE CERTIFICATE_TYPE_CODE = 'AI';
-- O
UPDATE CERTIFICATE_TYPE_CODE SET DESCRIPTION = 'B.C. Certificate of Graduation - Offshore School Program'
WHERE CERTIFICATE_TYPE_CODE = 'O';

