UPDATE REPORT_TYPE_CODE SET LABEL='Projected Non-Graduates - Summary Report (MM YYYY to MM YYYY)' WHERE REPORT_TYPE_CODE='NONGRADPRJ';
UPDATE REPORT_TYPE_CODE SET LABEL='Not-Yet Graduated Students (MM YYYY to MM YYYY) Report' WHERE REPORT_TYPE_CODE='NONGRADREG';
UPDATE REPORT_TYPE_CODE SET LABEL='Graduated Students (MM YYYY to MM YYYY) Report' WHERE REPORT_TYPE_CODE='GRADREG';



