UPDATE REPORT_TYPE_CODE SET LABEL='TVR' DESCRIPTION='Student Transcript Verification Report' WHERE REPORT_TYPE_CODE='ACHV';
Insert into REPORT_TYPE_CODE (REPORT_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) values ('XML','XML Transcript','XML Transcript Data',30,to_date('21-07-19','RR-MM-DD'),to_date('99-12-31','RR-MM-DD'));
