UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Sylvia Russell', UPDATE_USER = 'GRAD_REPORT_API', UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='040';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Karim Hachlaf', UPDATE_USER = 'GRAD_REPORT_API', UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='041';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Matthew Monkman', UPDATE_USER = 'GRAD_REPORT_API', UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='092';
