UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Geoff Manning', UPDATE_USER = USER, UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='072';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Pascale Bernier', UPDATE_USER = USER, UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='093';
