UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Pam Spooner' WHERE DIGITAL_SIGNATURE_CODE='057';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Mark Theobald' WHERE DIGITAL_SIGNATURE_CODE='081';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Geoff Manning' WHERE DIGITAL_SIGNATURE_CODE='071';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Rick Ryan' WHERE DIGITAL_SIGNATURE_CODE='038';