--------------------------------------------------------
--  DDL for Table REPORT_TYPE_CODE
--------------------------------------------------------

CREATE TABLE REPORT_TYPE_CODE
(	REPORT_TYPE_CODE VARCHAR2(10 BYTE),
     LABEL VARCHAR2(50 BYTE),
     DESCRIPTION VARCHAR2(255 BYTE),
     DISPLAY_ORDER NUMBER,
     EFFECTIVE_DATE DATE,
     EXPIRY_DATE DATE,
     CREATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     CREATE_DATE DATE DEFAULT SYSTIMESTAMP,
     UPDATE_USER VARCHAR2(30 BYTE) DEFAULT USER,
     UPDATE_DATE DATE DEFAULT SYSTIMESTAMP,
     CONSTRAINT REPORT_TYPE_CODE_PK PRIMARY KEY (REPORT_TYPE_CODE)
         USING INDEX TABLESPACE API_GRAD_IDX  ENABLE
) SEGMENT CREATION IMMEDIATE
    NOCOMPRESS LOGGING
    TABLESPACE API_GRAD_DATA   NO INMEMORY ;


