UPDATE PROGRAM_CERTIFICATE_TRANSCRIPT
SET SCHOOL_CATEGORY_CODE='01'
WHERE GRADUATION_PROGRAM_CODE='FI' AND CERTIFICATE_TYPE_CODE='F';

INSERT INTO PROGRAM_CERTIFICATE_TRANSCRIPT (PROGRAM_CERT_TRANS_ID,GRADUATION_PROGRAM_CODE,SCHOOL_CATEGORY_CODE,CERTIFICATE_TYPE_CODE,TRANSCRIPT_TYPE_CODE)
values (SYS_GUID(),'FI','02','FIND',NULL);

