ALTER TABLE SCHOOL_REPORT ADD (
    DISTRIBUTION_DATE DATE
);

ALTER TABLE SCHOOL_REPORT MODIFY (CREATE_USER INVISIBLE, CREATE_DATE INVISIBLE, UPDATE_USER INVISIBLE, UPDATE_DATE INVISIBLE);
ALTER TABLE SCHOOL_REPORT MODIFY (CREATE_USER VISIBLE, CREATE_DATE VISIBLE, UPDATE_USER VISIBLE, UPDATE_DATE VISIBLE);