CREATE INDEX X_STUDTRANS_ID_DOC
ON STUDENT_TRANSCRIPT (
    GRADUATION_STUDENT_RECORD_ID
    ,DOCUMENT_STATUS_CODE
)
TABLESPACE API_GRAD_IDX;

CREATE INDEX X_STUDTRANS_ID_TRAN
ON STUDENT_TRANSCRIPT (
    GRADUATION_STUDENT_RECORD_ID
    ,TRANSCRIPT_TYPE_CODE
)
TABLESPACE API_GRAD_IDX;

CREATE INDEX X_STUDTRANS_ID_TRAN_DOC
ON STUDENT_TRANSCRIPT (
    GRADUATION_STUDENT_RECORD_ID
    ,TRANSCRIPT_TYPE_CODE
    ,DOCUMENT_STATUS_CODE
)
TABLESPACE API_GRAD_IDX;

CREATE BITMAP INDEX X_STUDTRANS_TRAN
ON STUDENT_TRANSCRIPT (TRANSCRIPT_TYPE_CODE)
TABLESPACE API_GRAD_IDX;

CREATE BITMAP INDEX X_STUDTRANS_DOC
ON STUDENT_TRANSCRIPT (DOCUMENT_STATUS_CODE)
TABLESPACE API_GRAD_IDX;

CREATE BITMAP INDEX X_STUDCERT_CERT
ON STUDENT_CERTIFICATE (CERTIFICATE_TYPE_CODE)
TABLESPACE API_GRAD_IDX;

CREATE BITMAP INDEX X_STUDCERT_DOC
ON STUDENT_CERTIFICATE (DOCUMENT_STATUS_CODE)
TABLESPACE API_GRAD_IDX;

CREATE INDEX X_STUDCERT_ID_CERT
ON STUDENT_CERTIFICATE (
    GRADUATION_STUDENT_RECORD_ID
    ,CERTIFICATE_TYPE_CODE
)
TABLESPACE API_GRAD_IDX;

CREATE INDEX X_STUDCERT_ID_CERT_DOC
ON STUDENT_CERTIFICATE (
    GRADUATION_STUDENT_RECORD_ID
    ,CERTIFICATE_TYPE_CODE
    ,DOCUMENT_STATUS_CODE
)
TABLESPACE API_GRAD_IDX;



