UPDATE CERTIFICATE_TYPE_CODE SET DISPLAY_ORDER=10 WHERE CERTIFICATE_TYPE_CODE='F';
UPDATE CERTIFICATE_TYPE_CODE SET DISPLAY_ORDER=20 WHERE CERTIFICATE_TYPE_CODE='E';
UPDATE CERTIFICATE_TYPE_CODE SET DISPLAY_ORDER=30 WHERE CERTIFICATE_TYPE_CODE='EI';
UPDATE CERTIFICATE_TYPE_CODE SET DISPLAY_ORDER=40 WHERE CERTIFICATE_TYPE_CODE='S';
UPDATE CERTIFICATE_TYPE_CODE SET DISPLAY_ORDER=50 WHERE CERTIFICATE_TYPE_CODE='A';
UPDATE CERTIFICATE_TYPE_CODE SET DISPLAY_ORDER=60 WHERE CERTIFICATE_TYPE_CODE='AI';
UPDATE CERTIFICATE_TYPE_CODE SET DISPLAY_ORDER=70 WHERE CERTIFICATE_TYPE_CODE='SC';
UPDATE CERTIFICATE_TYPE_CODE SET DISPLAY_ORDER=80 WHERE CERTIFICATE_TYPE_CODE='O';
UPDATE CERTIFICATE_TYPE_CODE SET DISPLAY_ORDER=90 WHERE CERTIFICATE_TYPE_CODE='SCF';
UPDATE CERTIFICATE_TYPE_CODE SET DISPLAY_ORDER=100 WHERE CERTIFICATE_TYPE_CODE='SCI';

INSERT INTO CERTIFICATE_TYPE_CODE (CERTIFICATE_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, PAPER_TYPE, "LANGUAGE") VALUES('FN', 'First Nations', 'B.C. Certificate of Graduation – First Nations', 110, TIMESTAMP '2021-07-19 00:00:00.000000', NULL, 'YEDR', 'English');
INSERT INTO CERTIFICATE_TYPE_CODE (CERTIFICATE_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, PAPER_TYPE, "LANGUAGE") VALUES('FNA', 'Adult Dogwood (First Nations)', 'Adult Graduation Diploma - First Nations', 120, TIMESTAMP '2021-07-19 00:00:00.000000', NULL, 'YEDB', 'English');
INSERT INTO CERTIFICATE_TYPE_CODE (CERTIFICATE_TYPE_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE, PAPER_TYPE, "LANGUAGE") VALUES('SCFN', 'Evergreen (First Nations)', 'School Completion Certificate – First Nations', 130, TIMESTAMP '2021-07-19 00:00:00.000000', NULL, 'YED2', 'English');

UPDATE DIGITAL_SIGNATURE
SET DIGITAL_SIGNATURE_CODE='FIRST_NATIONS'
WHERE DIGITAL_SIGNATURE_KEY='B2F49998805641BC81EAC37F3BA75E15';

DELETE FROM PROGRAM_CERTIFICATE_TRANSCRIPT WHERE GRADUATION_PROGRAM_CODE='SCCP' AND SCHOOL_CATEGORY_CODE='03' AND CERTIFICATE_TYPE_CODE='SC' AND TRANSCRIPT_TYPE_CODE='SCCP-EN';
DELETE FROM PROGRAM_CERTIFICATE_TRANSCRIPT WHERE GRADUATION_PROGRAM_CODE='2018-EN' AND SCHOOL_CATEGORY_CODE='03' AND CERTIFICATE_TYPE_CODE='E' AND TRANSCRIPT_TYPE_CODE='BC2018-PUB';
DELETE FROM PROGRAM_CERTIFICATE_TRANSCRIPT WHERE GRADUATION_PROGRAM_CODE='1950' AND SCHOOL_CATEGORY_CODE='03' AND CERTIFICATE_TYPE_CODE='A' AND TRANSCRIPT_TYPE_CODE='BC1950-PUB';
DELETE FROM PROGRAM_CERTIFICATE_TRANSCRIPT WHERE GRADUATION_PROGRAM_CODE='2004-EN' AND SCHOOL_CATEGORY_CODE='03' AND CERTIFICATE_TYPE_CODE='E' AND TRANSCRIPT_TYPE_CODE='BC2004-PUB';
DELETE FROM PROGRAM_CERTIFICATE_TRANSCRIPT WHERE GRADUATION_PROGRAM_CODE='1996-EN' AND SCHOOL_CATEGORY_CODE='03' AND CERTIFICATE_TYPE_CODE='E' AND TRANSCRIPT_TYPE_CODE='BC1996-PUB';
DELETE FROM PROGRAM_CERTIFICATE_TRANSCRIPT WHERE GRADUATION_PROGRAM_CODE='1986-EN' AND SCHOOL_CATEGORY_CODE='03' AND CERTIFICATE_TYPE_CODE='E' AND TRANSCRIPT_TYPE_CODE='BC1986-PUB';

UPDATE PROGRAM_CERTIFICATE_TRANSCRIPT SET CERTIFICATE_TYPE_CODE='FN' WHERE GRADUATION_PROGRAM_CODE='2023-EN' AND SCHOOL_CATEGORY_CODE='03' AND CERTIFICATE_TYPE_CODE='E' AND TRANSCRIPT_TYPE_CODE='BC2023-PUB';

INSERT INTO PROGRAM_CERTIFICATE_TRANSCRIPT (PROGRAM_CERT_TRANS_ID, GRADUATION_PROGRAM_CODE, SCHOOL_CATEGORY_CODE, CERTIFICATE_TYPE_CODE, TRANSCRIPT_TYPE_CODE) VALUES('F4AC726FEA510165E0539AE9228E446E', '2018-EN', '03', 'FN', 'BC2018-PUB');
INSERT INTO PROGRAM_CERTIFICATE_TRANSCRIPT (PROGRAM_CERT_TRANS_ID, GRADUATION_PROGRAM_CODE, SCHOOL_CATEGORY_CODE, CERTIFICATE_TYPE_CODE, TRANSCRIPT_TYPE_CODE) VALUES('F4AC7453C34F0450E05398E9228E90EB', '2004-EN', '03', 'FN', 'BC2004-PUB');
INSERT INTO PROGRAM_CERTIFICATE_TRANSCRIPT (PROGRAM_CERT_TRANS_ID, GRADUATION_PROGRAM_CODE, SCHOOL_CATEGORY_CODE, CERTIFICATE_TYPE_CODE, TRANSCRIPT_TYPE_CODE) VALUES('F4AC7453C3500450E05398E9228E90EB', '1996-EN', '03', 'FN', 'BC1996-PUB');
INSERT INTO PROGRAM_CERTIFICATE_TRANSCRIPT (PROGRAM_CERT_TRANS_ID, GRADUATION_PROGRAM_CODE, SCHOOL_CATEGORY_CODE, CERTIFICATE_TYPE_CODE, TRANSCRIPT_TYPE_CODE) VALUES('F4AC7453C3510450E05398E9228E90EB', '1986-EN', '03', 'FN', 'BC1986-PUB');
INSERT INTO PROGRAM_CERTIFICATE_TRANSCRIPT (PROGRAM_CERT_TRANS_ID, GRADUATION_PROGRAM_CODE, SCHOOL_CATEGORY_CODE, CERTIFICATE_TYPE_CODE, TRANSCRIPT_TYPE_CODE) VALUES('F4AC7453C3520450E05398E9228E90EB', '1950', '03', 'FNA', 'BC1950-PUB');
INSERT INTO PROGRAM_CERTIFICATE_TRANSCRIPT (PROGRAM_CERT_TRANS_ID, GRADUATION_PROGRAM_CODE, SCHOOL_CATEGORY_CODE, CERTIFICATE_TYPE_CODE, TRANSCRIPT_TYPE_CODE) VALUES('F4AC7453C3530450E05398E9228E90EB', 'SCCP', '03', 'SCFN', 'SCCP-EN');
