UPDATE PROGRAM_CERTIFICATE_TRANSCRIPT
SET CERTIFICATE_TYPE_CODE='S'
WHERE GRADUATION_PROGRAM_CODE='1986-PF' AND SCHOOL_CATEGORY_CODE='01' AND CERTIFICATE_TYPE_CODE='E';

DELETE FROM PROGRAM_CERTIFICATE_TRANSCRIPT
WHERE GRADUATION_PROGRAM_CODE = '1986-PF' AND SCHOOL_CATEGORY_CODE IN ('02', '03', '04', '09');

UPDATE PROGRAM_CERTIFICATE_TRANSCRIPT
SET TRANSCRIPT_TYPE_CODE = 'BC1996-PUB'
WHERE GRADUATION_PROGRAM_CODE='1996-EN' AND SCHOOL_CATEGORY_CODE='09' AND CERTIFICATE_TYPE_CODE='O';
