UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Marcus Toneatto', UPDATE_USER = 'GRAD_REPORT_API', UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='053';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Paul Block', UPDATE_USER = 'GRAD_REPORT_API', UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='062';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Jill Jensen', UPDATE_USER = 'GRAD_REPORT_API', UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='064';
UPDATE DIGITAL_SIGNATURE SET DIGITAL_SIGNATURE_NAME='Jennifer Wray', UPDATE_USER = 'GRAD_REPORT_API', UPDATE_DATE = SYSTIMESTAMP WHERE DIGITAL_SIGNATURE_CODE='MOE_ADM';
