ALTER TABLE CERTIFICATE_TYPE_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE CERTIFICATE_TYPE_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE DIGITAL_SIGNATURE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE DIGITAL_SIGNATURE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE DISTRICT_REPORT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE DISTRICT_REPORT
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE DOCUMENT_STATUS_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE DOCUMENT_STATUS_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE PROGRAM_CERTIFICATE_TRANSCRIPT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE PROGRAM_CERTIFICATE_TRANSCRIPT
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE REPORT_TYPE_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE REPORT_TYPE_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE SCHOOL_REPORT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE SCHOOL_REPORT
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE SIGNATURE_BLOCK_TYPE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE SIGNATURE_BLOCK_TYPE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE STUDENT_CERTIFICATE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE STUDENT_CERTIFICATE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE STUDENT_REPORT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE STUDENT_REPORT
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE STUDENT_TRANSCRIPT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE STUDENT_TRANSCRIPT
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE TRANSCRIPT_TYPE_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE TRANSCRIPT_TYPE_CODE
    MODIFY UPDATE_USER VARCHAR2(100);