#Spring boot Properties
#
spring:
  jmx:
    enabled: false
  datasource:
    hikari:
      pool-name: educ-grad-report-api-cp
      connection-timeout: ${CONNECTION_TIMEOUT}
      maximum-pool-size: ${MAXIMUM_POOL_SIZE}
      minimum-idle: ${MIN_IDLE}
      idle-timeout: ${IDLE_TIMEOUT}
      max-lifetime: ${MAX_LIFETIME}
    url: ${CONNECTION_STRING}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: ${SHOW_SQL_LOGS}
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  flyway:
    enabled: ${ENABLE_FLYWAY}
    baseline-on-migrate: false
    table: FLYWAY_SCHEMA_HISTORY
    url: ${CONNECTION_STRING}
    user: ${USERNAME}
    password: ${PASSWORD}
    locations: classpath:db/migration
  messages:
    basename: messages
  #Keycloak/OAuth properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URL}
          jwk-set-uri: ${TOKEN_ISSUER_URL}/protocol/openid-connect/certs
#Logging properties
logging:
  file:
    name: /logs/app.log
  pattern:
    file: '{"time_stamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%3p" ,"thread":"%t" ,"class":"%logger{36}","msg":"%replace(%msg){"[\n\r\"]",""}", "exception":"%replace(%rEx{10}){"[\n\r\"]",""}","http_event":%X{httpEvent:-""},"message_event":%X{messageEvent:-""}}%nopex%n'
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] [%t] [%logger{36}] [%replace(%msg){'[\n\r\"]',''} %X{httpEvent} %X{messageEvent}] %replace(%rEx{10}){'[\n\r\"]',''}%nopex%n"
  level:
    ca:
      bc:
        gov:
          educ:
            grad:
              report: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}
    com:
      zaxxer:
        hikari: ERROR
  logback:
    rollingpolicy:
      max-history: 1
      clean-history-on-start: true
      max-file-size: 20MB

splunk:
  log-helper:
    enabled: ${ENABLE_SPLUNK_LOG_HELPER}

#Local properties
server:
  undertow:
    threads:
      worker: 128
      io: 16
  #port: ${HTTP_PORT}

#API Documentation
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs-ui.html
    operationsSorter: alpha

#Endpoint properties
endpoint:
  educ-grad-report-api:
    get-signature-by-code:
      url: ${GRAD_REPORT_API}api/v1/reports/signatures
  educ-grad-trax-api:
    get-district-details:
      url: ${GRAD_TRAX_API}api/v1/trax/district/%s
    school-by-min-code:
      url: ${GRAD_TRAX_API}api/v1/trax/school/%s
    country-by-code:
      url: ${GRAD_TRAX_API}api/v1/trax/code/country/%s
  grad-student-api:
    read-grad-student-record:
      url: ${GRAD_STUDENT_API}api/v1/student/studentid/%s
    read-grad-student-record-pen:
        url: ${GRAD_STUDENT_API}api/v1/student/pen/%s
  pen-student-api:
    by-studentid:
      url: ${PEN_API}api/v1/student/%s
    by-pen:
      url: ${PEN_API}api/v1/student?pen=%s
  grad-program-api:
    program-name-by-program_code:
      url: ${GRAD_PROGRAM_API}api/v1/program/programs/%s