#Spring boot Properties
#
spring:
  jmx:
    enabled: false
  datasource:
    hikari:
      pool-name: educ-grad-report-api-cp
      max-lifetime: ${MAX_LIFETIME}
    url: ${CONNECTION_STRING}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    show-sql: ${SHOW_SQL_LOGS}
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  flyway:
    enabled: ${ENABLE_FLYWAY}
    baseline-on-migrate: false
    table: FLYWAY_SCHEMA_HISTORY
    url: ${CONNECTION_STRING}
    user: ${USERNAME}
    password: ${PASSWORD}
    locations: classpath:db/migration
  messages:
    basename: messages
  #Keycloak/OAuth properties
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URL}
          jwk-set-uri: ${TOKEN_ISSUER_URL}/protocol/openid-connect/certs
      client:
        registration:
          report-api-client:
            client-id: ${GRAD_REPORT_API_CLIENT_NAME}
            client-secret: ${GRAD_REPORT_API_CLIENT_SECRET}
            authorization-grant-type: client_credentials
          grad-report-educ-student-api-client:
            client-id: ${GRAD_REPORT_EDUC_STUDENT_API_CLIENT_NAME}
            client-secret: ${GRAD_REPORT_EDUC_STUDENT_API_CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          report-api-client:
            issuer-uri: ${TOKEN_ISSUER_URL}
            token-uri: ${TOKEN_ISSUER_URL}/protocol/openid-connect/token
          grad-report-educ-student-api-client:
            issuer-uri: ${TOKEN_ISSUER_URL}
            token-uri: ${TOKEN_ISSUER_URL}/protocol/openid-connect/token

#Logging properties
logging:
  file:
    name: /logs/app.log
  pattern:
    file: '{"time_stamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%3p" ,"thread":"%t" ,"class":"%logger{36}","msg":"%replace(%msg){"[\n\r\"]",""}", "exception":"%replace(%rEx{10}){"[\n\r\"]",""}","http_event":%X{httpEvent:-""},"message_event":%X{messageEvent:-""}}%nopex%n'
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] [%t] [%logger{36}] [%replace(%msg){'[\n\r\"]',''} %X{httpEvent} %X{messageEvent}] %replace(%rEx{10}){'[\n\r\"]',''}%nopex%n"
  level:
    ca:
      bc:
        gov:
          educ:
            grad:
              report: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}
    com:
      zaxxer:
        hikari: ERROR
  logback:
    rollingpolicy:
      max-history: 1
      clean-history-on-start: true
      max-file-size: 20MB

splunk:
  log-helper:
    enabled: ${ENABLE_SPLUNK_LOG_HELPER}

#Local properties
server:
  undertow:
    threads:
      worker: 128
      io: 16
  #port: ${HTTP_PORT}
  max-http-request-header-size: 20000
  compression:
    enabled: ${ENABLE_COMPRESSION}
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
    min-response-size: 2048
    excluded-user-agents: MSIE 6.0,UCBrowser

#API Documentation
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs-ui.html
    operationsSorter: alpha

#Endpoint properties
endpoint:
  keycloak:
    getToken: ${KEYCLOAK_TOKEN_URL}auth/realms/master/protocol/openid-connect/token
  educ-grad-report-api:
    get-signature-by-code:
      url: ${GRAD_REPORT_API}api/v1/reports/signatures
  educ-grad-trax-api:
    get-district-details:
      url: ${GRAD_TRAX_API}api/v2/trax/district?distNo=%s
    school-by-school-id:
      url: ${GRAD_TRAX_API}api/v2/trax/school-clob/%s
  grad-student-api:
    read-grad-student-record:
      url: ${GRAD_STUDENT_API}api/v1/student/studentid/%s
    read-grad-student-record-pen:
      url: ${GRAD_STUDENT_API}api/v1/student/pen/%s
  pen-student-api:
    by-studentid:
      url: ${PEN_API}api/v1/student/%s
    by-pen:
      url: ${PEN_API}api/v1/student?pen=%s
  grad-program-api:
    program-name-by-program_code:
      url: ${GRAD_PROGRAM_API}api/v1/program/programs/%s