net.sf.jasperreports.extension.registry.factory.fonts=net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory
net.sf.jasperreports.extension.simple.font.families.ireportfamily1531324152650=fonts/fontsfamily.xml
net.sf.jasperreports.export.pdf.glyph.renderer.blocks.indigenous=COMBINING_DIACRITICAL_MARKS,IPA_EXTENSIONS,SPACING_MODIFIER_LETTERS,PHONETIC_EXTENSIONS
net.sf.jasperreports.export.pdf.glyph.renderer.add.actual.text=true
