/*
 * *********************************************************************
 *  Copyright (c) 2017, Ministry of Education and Child Care, BC.
 *
 *  All rights reserved.
 *    This information contained herein may not be used in whole
 *    or in part without the express written consent of the
 *    Government of British Columbia, Canada.
 *
 *  Revision Control Information
 *  File:                $Id::                                                 $
 *  Date of Last Commit: $Date::                                               $
 *  Revision Number:     $Rev::                                                $
 *  Last Commit by:      $Author::                                             $
 *
 * ***********************************************************************
 */
package ca.bc.gov.educ.grad.report.service.impl;

import ca.bc.gov.educ.grad.report.api.client.ReportData;
import ca.bc.gov.educ.grad.report.dao.GradDataConvertionBean;
import ca.bc.gov.educ.grad.report.dao.ProgramCertificateTranscriptRepository;
import ca.bc.gov.educ.grad.report.dao.ReportRequestDataThreadLocal;
import ca.bc.gov.educ.grad.report.dto.impl.*;
import ca.bc.gov.educ.grad.report.entity.ProgramCertificateTranscriptEntity;
import ca.bc.gov.educ.grad.report.exception.EntityNotFoundException;
import ca.bc.gov.educ.grad.report.model.common.DataException;
import ca.bc.gov.educ.grad.report.model.common.DomainServiceException;
import ca.bc.gov.educ.grad.report.model.graduation.GradProgram;
import ca.bc.gov.educ.grad.report.model.graduation.GraduationProgramCode;
import ca.bc.gov.educ.grad.report.model.graduation.NonGradReason;
import ca.bc.gov.educ.grad.report.model.reports.*;
import ca.bc.gov.educ.grad.report.model.school.School;
import ca.bc.gov.educ.grad.report.model.student.PersonalEducationNumber;
import ca.bc.gov.educ.grad.report.model.student.Student;
import ca.bc.gov.educ.grad.report.model.student.StudentInfo;
import ca.bc.gov.educ.grad.report.model.transcript.*;
import org.apache.commons.lang3.NotImplementedException;
import org.apache.commons.lang3.builder.CompareToBuilder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.AsyncResult;
import org.springframework.stereotype.Service;

import javax.annotation.security.DeclareRoles;
import javax.annotation.security.RolesAllowed;
import java.io.IOException;
import java.text.NumberFormat;
import java.util.*;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;

import static ca.bc.gov.educ.grad.report.dto.impl.RequirementNames.getName;
import static ca.bc.gov.educ.grad.report.dto.impl.constants.Roles.STUDENT_TRANSCRIPT_REPORT;
import static ca.bc.gov.educ.grad.report.model.common.support.VerifyUtils.nullSafe;
import static ca.bc.gov.educ.grad.report.model.common.support.impl.Roles.FULFILLMENT_SERVICES_USER;
import static ca.bc.gov.educ.grad.report.model.common.support.impl.Roles.USER;
import static ca.bc.gov.educ.grad.report.model.course.ReportCourseType.ASSESSMENT;
import static ca.bc.gov.educ.grad.report.model.course.ReportCourseType.PROVINCIALLY_EXAMINABLE;
import static ca.bc.gov.educ.grad.report.model.reports.ReportFormat.PDF;
import static java.text.NumberFormat.getIntegerInstance;
import static org.apache.commons.lang3.ArrayUtils.isEmpty;

/**
 * The transcript service is an implementation component of the broader
 * Transcript Services group. As part of the mid-tier service layer the
 * buildReport method called by the GUI (browser) to display the unofficial
 * transcript of grades. The display is a rendered report generated by the
 * report service populated with data from the TRAX adaptor for the current user
 * as determined by the student demographics service.
 * <p>
 * This service integrates with the Student Demographics, the TRAX adaptor, and
 * the Reporting Service.
 * </p>
 *
 * The security roles required to build a transcript report are:
 * <ol>
 * <li>XS_REPORT</li>
 * <li>TRAX_READ</li>
 * <li>SXR_READ</li>
 * <li>SXR_SEARCH</li>
 * <li>USER_REPORTS_EXPORT</li>
 * <li>USER_REPORTS_TRANSCRIPT</li>
 * <li>USER_PROFILE_SEARCH</li>
 * <li>USER_PROFILE_READ</li>
 * <li>USER</li>
 * </ol>
 *
 * @author CGI Information Management Consultants Inc.
 */
@Service
@DeclareRoles({STUDENT_TRANSCRIPT_REPORT, USER, FULFILLMENT_SERVICES_USER})
public class StudentTranscriptServiceImpl extends GradReportServiceImpl implements StudentTranscriptService {

    private static final long serialVersionUID = 5L;

    private static final String CLASSNAME = StudentTranscriptServiceImpl.class.getName();
    private static final Logger LOG = Logger.getLogger(CLASSNAME);
    private static final String REPORT_DATA_MISSING = "REPORT_DATA_MISSING";

    /**
     * Sort order for ungraded courses (to bottom, above assessments).
     */
    private static final String SORT_UNGRADED = "99";

    /**
     * Sort order for assessments (to bottom, below ungraded).
     */
    private static final String SORT_ASSESSMENT = "100";

    @Autowired
    private ReportService reportService;

    @Autowired
    private GradDataConvertionBean gradDataConvertionBean;

    @Autowired
    private ProgramCertificateTranscriptRepository programCertificateTranscriptRepository;

    /**
     * Creates the student's official transcript as a PDF (no other formats are
     * allowed for official transcripts).
     *
     * @return A filled transcript report suitable for sending to a PSI.
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    @Override
    @RolesAllowed({STUDENT_TRANSCRIPT_REPORT, USER})
    public StudentTranscriptReport buildOfficialTranscriptReport()
            throws DomainServiceException, IOException, DataException {
        return createTranscriptReport(PDF, false);
    }

    /**
     * Builds an unofficial transcript report asynchronously. Calls
     * <code>createTranscriptReport(ReportFormat, true)</code> and returns the
     * result wrapped in an AsyncResult.
     *
     * @param format PDF, HTML, etc.
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    @Override
    @RolesAllowed({STUDENT_TRANSCRIPT_REPORT, USER})
    public Future<StudentTranscriptReport> buildTranscriptReportAsync(
            final ReportFormat format)
            throws DomainServiceException, IOException, DataException {
        return new AsyncResult<>(createTranscriptReport(format, true));
    }

    @Override
    @RolesAllowed({STUDENT_TRANSCRIPT_REPORT, USER})
    public Transcript getTranscript() throws DomainServiceException {
        final String methodName = "getTranscript()";
        LOG.entering(CLASSNAME, methodName);

        final String pen = getStudentPENId();
        final Transcript transcript = getTranscript(pen);

        LOG.exiting(CLASSNAME, methodName);
        return transcript;
    }

    @Override
    @RolesAllowed({STUDENT_TRANSCRIPT_REPORT, USER})
    public Transcript getTranscript(
            final String pen) throws DomainServiceException {
        final String methodName = "getTranscript(String)";
        LOG.entering(CLASSNAME, methodName);

        final Transcript transcriptInfo = getTranscriptInformation(pen);
        final List<TranscriptCourse> transcriptCourses = getTranscriptCourseList(pen, transcriptInfo.getInterim());
        final StudentInfo studentInfo = getStudentInfo(pen);
        final TranscriptTypeCode transcriptTypeCode = transcriptInfo.getTranscriptTypeCode();
        final GradProgram program = createGradProgram(studentInfo.getGradReqYear());
        final Date reportDate = transcriptInfo.getIssueDate();

        final Transcript transcript = adapt(
                transcriptTypeCode,
                program.getCode(),
                transcriptCourses,
                reportDate,
                transcriptInfo.getInterim()
        );

        LOG.exiting(CLASSNAME, methodName);
        return transcript;
    }

    @Override
    @RolesAllowed({STUDENT_TRANSCRIPT_REPORT, USER})
    public Transcript getTranscriptInformation(final String pen) throws DomainServiceException {
        final String methodName = "getTranscriptInformation(String)";
        LOG.entering(CLASSNAME, methodName);

        final Transcript transcript;

        try {
            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        getClass(),
                        REPORT_DATA_MISSING,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, methodName, dse);
                throw dse;
            }

            transcript = gradDataConvertionBean.getTranscript(reportData);

        } catch (Exception ex) {
            String msg = "Failed to access transcript data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, methodName, dex);
            throw dex;
        }

        LOG.exiting(CLASSNAME, methodName);
        return transcript;
    }

    private GradProgram createGradProgram(String code) {
        final String methodName = "createGradProgram(String)";
        LOG.entering(CLASSNAME, methodName);

        final GradProgram gradProgram;

        try {
            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        getClass(),
                        REPORT_DATA_MISSING,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, methodName, dse);
                throw dse;
            }

            if (reportData.getGradProgram() == null || reportData.getGradProgram().getCode() == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        getClass(),
                        "GRAD_PROGRAM_MISSING",
                        "Grad Program or Grad Program Code is null");
                LOG.throwing(CLASSNAME, methodName, dse);
                throw dse;
            }

            gradProgram = new GradProgramImpl(GraduationProgramCode.valueFrom(
                    code,
                    reportData.getGradProgram().getCode().getDescription()));

        } catch (Exception ex) {
            String msg = "Failed to get grad program : ".concat(code);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, methodName, dex);
            throw dex;
        }

        return gradProgram;
    }

    /**
     * Creates a report in a specific format, either official or unofficial,
     * depending on the preview value.
     *
     * @param format
     * @param preview Set to false to create an unofficial transcript
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    private StudentTranscriptReport createTranscriptReport(
            final ReportFormat format,
            final boolean preview)
            throws DomainServiceException, IOException, DataException {
        final String methodName = "createTranscript(ReportFormat, boolean)";
        LOG.entering(CLASSNAME, methodName);

        final PersonalEducationNumber pen = getStudentPEN();
        LOG.log(Level.FINE, "Retrieved studentInfo for pen: {0}.", pen.getValue());

        final StudentTranscriptReport report = getStudentTranscriptReport(
                pen, format, preview, null
        );
        LOG.exiting(CLASSNAME, methodName);
        return report;
    }

    /**
     * Creates a report in a specific format, either official or unofficial,
     * depending on the preview value. Takes the PEN to generate the desired
     * report.
     *
     * @param format
     * @param preview Set to false to create an unofficial transcript
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    private StudentTranscriptReport createTranscriptReport(
            final ReportFormat format,
            final boolean preview, final PersonalEducationNumber pen, final Parameters<String, Object> parameters)
            throws DomainServiceException, IOException, DataException {
        final String methodName = "createTranscript(ReportFormat, boolean)";
        LOG.entering(CLASSNAME, methodName);
        LOG.log(Level.FINE, "Retrieved transcript for pen: {0}.", pen.getValue());

        final StudentTranscriptReport report = getStudentTranscriptReport(pen, format, preview, parameters);
        LOG.log(Level.INFO, "Created StudentTranscriptReport for pen: {0}.", pen.getValue());

        LOG.exiting(CLASSNAME, methodName);
        return report;
    }

    private String getStudentPENId() throws DomainServiceException {
        final String methodName = "getStudentPENId()";
        LOG.entering(CLASSNAME, methodName);

        final PersonalEducationNumber pen = getStudentPEN();
        final String result = pen.getValue();

        LOG.exiting(CLASSNAME, methodName);
        return result;
    }

    /**
     * Read the collection of transcript courses from the TRAX Adaptor which is
     * required for the transcript service.
     *
     * @param pen Student identifier.
     *
     * @return
     */
    private List<TranscriptCourse> getTranscriptCourseList(
            final String pen, final boolean interim)
            throws DataException, DomainServiceException {
        final String m_ = "getTranscriptCourseList(String, boolean)";
        LOG.entering(CLASSNAME, m_);

        final List<TranscriptCourse> results;

        try {

            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        getClass(),
                        REPORT_DATA_MISSING,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, m_, dse);
                throw dse;
            }

            if(interim) {
                results = filterCourses(gradDataConvertionBean.getTranscriptCourses(reportData));
            } else {
                results = gradDataConvertionBean.getTranscriptCourses(reportData);
            }

            LOG.log(Level.INFO,
                    "Retrieved the collection of exam results for PEN: {0} INTERIM: {1}",
                    new Object[]{pen, interim});

            if (results != null && !results.isEmpty()) {
                LOG.log(Level.INFO,
                        "Total courses {0} retrieved  for PEN: {1}",
                        new Object[]{results.size(), pen});
                LOG.log(Level.FINEST, "Retrieved student transcript course results:");
                for (TranscriptCourse result : results) {
                    LOG.log(Level.FINEST, "{0} {1}",
                            new Object[]{result.getCourseName(), result.getFinalLetterGrade()});
                }
            }
        } catch (final Exception ex) {
            String msg = "Failed to access transcript course data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, m_, dex);
            throw dex;
        }

        LOG.log(Level.FINE, "Completed call to TRAX.");
        LOG.exiting(CLASSNAME, m_);
        return results;
    }

    /**
     * Adapt the TRAX data from the collection of data value objects into a
     * Transcript object.
     *
     * @param transcriptTypeCode
     * @param graduationProgramCode The graduation program code that influences sort order.
     * @param transcriptCourses
     * @param issueDate
     */
    private Transcript adapt(
            final TranscriptTypeCode transcriptTypeCode,
            final GraduationProgramCode graduationProgramCode,
            final List<TranscriptCourse> transcriptCourses,
            final Date issueDate,
            final boolean interim) {
        final String m_ = "adapt(GraduationProgramCode, List<TranscriptCourse>, Date, boolean)";
        LOG.entering(CLASSNAME, m_, transcriptCourses);

        final List<TranscriptResult> transcriptResults = adapt(
                graduationProgramCode, transcriptCourses);

        final TranscriptImpl transcript = new TranscriptImpl();
        transcript.setTranscriptTypeCode(transcriptTypeCode);
        transcript.setIssueDate(issueDate);
        transcript.setResults(transcriptResults);
        transcript.setInterim(interim);

        LOG.exiting(CLASSNAME, m_);
        return transcript;
    }

    /**
     * Adapt the TRAX data from the collection of data value objects into a
     * Transcript object.
     *
     * @param schoolCategoryCode
     * @param transcriptTypeCode
     * @param graduationProgramCode The graduation program code that influences sort order.
     */
    private GradProgram adapt(
            final String schoolCategoryCode,
            final String graduationProgramCode,
            final TranscriptTypeCode transcriptTypeCode,
            final String accessToken) {
        final String m_ = "adapt(schoolCategoryCode, graduationProgramCode,transcriptTypeCode )";
        LOG.entering(CLASSNAME, m_, transcriptTypeCode);

        GradProgram result = createGradProgram(graduationProgramCode);

        try {
            if("BLANK".equalsIgnoreCase(graduationProgramCode) && transcriptTypeCode != null && schoolCategoryCode != null) {
                List<ProgramCertificateTranscriptEntity> entities = programCertificateTranscriptRepository.findBySchoolCategoryCodeAndTranscriptTypeCode(transcriptTypeCode.getCode());
                if(!entities.isEmpty()) {
                    GradProgramImpl gradProgram = getGraduationProgram(entities.get(0).getGraduationProgramCode(), accessToken);
                    if(gradProgram != null) {
                        gradProgram.setCode();
                        result = gradProgram;
                    }
                }
            }
        } catch (final Exception ex) {
            String msg = "Failed to get graduation program code from transcript type code and school category %s, %s, %s ";
            final DataException dex = new DataException(null, null, String.format(msg, schoolCategoryCode, transcriptTypeCode, graduationProgramCode), ex);
            LOG.throwing(CLASSNAME, m_, dex);
            throw dex;
        }

        LOG.exiting(CLASSNAME, m_);
        return result;
    }

    /**
     * Adapt the TRAX data from the collection of data value objects into a
     * Transcript object.
     *
     * @param programCode The graduation program code that influences sort
     * order.
     * @param transcriptCourses
     */
    private List<TranscriptResult> adapt(
            final GraduationProgramCode programCode,
            final List<TranscriptCourse> transcriptCourses) {
        final String m_ = "adapt(GraduationProgramCode, List<TranscriptCourse>)";
        LOG.entering(CLASSNAME, m_, transcriptCourses);

        List<TranscriptResult> transcriptResults = Collections.emptyList();

        if (transcriptCourses != null) {
            final int size = transcriptCourses.size();
            transcriptResults = new ArrayList<>(size);

            for (final TranscriptCourse transcriptCourse : transcriptCourses) {
                final String courseType = transcriptCourse.getCourseType();

                final String eq = transcriptCourse.getEquivalency();
                final String req = transcriptCourse.getRequirement();
                final String ufg = transcriptCourse.getUsedForGrad();
                final String reqName = getName(req, programCode.toString());
                final TranscriptResultImpl tResult = new TranscriptResultImpl(
                        req, eq, ufg, reqName);

                final String courseName = transcriptCourse.getCourseName();
                final String courseCode = transcriptCourse.getCourseCode();
                final String courseLevel = transcriptCourse.getCourseLevel();
                final String traxCredits = transcriptCourse.getCredits();
                final String relatedCourse = transcriptCourse.getRelatedCourse();
                final String relatedLevel = transcriptCourse.getRelatedLevel();

                final String sessionDate = transcriptCourse.getSessionDate();
                final CourseImpl course = new CourseImpl(
                        courseName, courseCode,
                        courseLevel, traxCredits,
                        sessionDate, courseType,
                        relatedCourse, relatedLevel);

                tResult.setCourse(course);

                final String schoolPct = transcriptCourse.getSchoolPercent();
                final String examPct = transcriptCourse.getExamPercent();
                String finalPct = transcriptCourse.getFinalPercent();
                final String finalLetterGrade = transcriptCourse.getFinalLetterGrade();
                final String interimPct = transcriptCourse.getInterimMark();
                final String interimLetterGrade = transcriptCourse.getInterimLetterGrade();

                final MarkImpl mark = new MarkImpl();
                mark.setSchoolPercent(schoolPct);
                mark.setExamPercent(examPct);

                // Marks should only contain interim OR final
                if ("0".equals(finalPct)) {
                    finalPct = "";
                }

                if (finalPct.isEmpty() && finalLetterGrade.isEmpty()) {
                    mark.setInterimLetterGrade(interimLetterGrade);
                    mark.setInterimPercent(interimPct);
                } else {
                    mark.setFinalLetterGrade(finalLetterGrade);
                    mark.setFinalPercent(finalPct);
                }

                tResult.setMark(mark);
                transcriptResults.add(tResult);
            }

            sort(transcriptResults, programCode);
        }

        LOG.exiting(CLASSNAME, m_);
        return transcriptResults;
    }

    /**
     * Convert non-graduation reasons from a TRAX map to an STs list.
     *
     * @param studentInfo The student instance that has non-grad reasons to
     * convert.
     *
     * @return The map of non-grad reasons converted from a map to a list of
     * NonGradReasons instances.
     */
    private List<NonGradReason> adaptReasons(final StudentInfo studentInfo) {
        final String methodName = "adaptReasons(StudentInfo)";
        LOG.entering(CLASSNAME, methodName);

        final Map<String, String> nonGradReasons = studentInfo.getNonGradReasons();
        final List<NonGradReason> result = new ArrayList<>();

        for (Map.Entry<String, String> entry : nonGradReasons.entrySet()) {
            final String key = entry.getKey();
            final String value = entry.getValue();
            NonGradReasonImpl r = new NonGradReasonImpl();
            r.setCode(key);
            r.setDescription(value);
            result.add(r);
        }

        LOG.exiting(CLASSNAME, methodName);
        return result;
    }

    /**
     * Create an unofficial transcript of grades report.
     *
     * @param reportFormat
     * @param preview
     * @param student
     * @param school
     * @param logo
     * @param transcript
     * @param program
     * @param nonGradReasons
     * @param gradMessage
     *
     * @return
     *
     * @throws DomainServiceException
     */
    private synchronized StudentTranscriptReport createReport(
            final ReportFormat reportFormat,
            final boolean preview,
            final Student student,
            final School school,
            final String logo,
            final ca.bc.gov.educ.grad.report.model.transcript.Transcript transcript,
            final GradProgram program,
            final List<NonGradReason> nonGradReasons,
            final String gradMessage,
            final Date updateDt,
            final Parameters<String, Object> parameters,
            final GraduationData graduationData) throws DomainServiceException, IOException {
        final String methodName = "createReport(...)";
        LOG.entering(CLASSNAME, methodName);

        final TranscriptTypeCode transcriptTypeCode = transcript.getTranscriptTypeCode();

        final TranscriptReport report = reportService.createTranscriptReport(transcriptTypeCode, program);

        if (parameters != null) {
            report.setParameters(parameters);
        }

        // Indicate official/unofficial
        report.setPreview(preview);

        report.setStudent(student);
        report.setSchool(school, logo);
        report.setGraduationProgram(program);
        report.setTranscript(transcript);
        report.setGraduationStatus(nonGradReasons, gradMessage);
        report.setReportDate(updateDt);
        report.setFormat(reportFormat);
        report.setGraduationData(graduationData);

        final boolean interim = ((TranscriptImpl) transcript).getInterim();
        report.setInterim(interim);

        final ReportDocument document;

        try {
            ca.bc.gov.educ.grad.report.dto.reports.data.impl.Student stu = (ca.bc.gov.educ.grad.report.dto.reports.data.impl.Student)report.getDataSource();
            document = reportService.export(report);
        } catch (final Exception ex) {
            final String msg = "Failed to create report.";
            LOG.log(Level.SEVERE, msg, ex);
            final DomainServiceException dse = new DomainServiceException(msg, ex);
            LOG.throwing(CLASSNAME, methodName, dse);
            throw dse;
        }
        LOG.log(Level.FINE, "Created document {0} for student {1}.", new Object[]{document, student.getPen()});

        final String filename = report.getFilename();
        final byte[] content = document.asBytes();

        if (isEmpty(content)) {
            final String msg = "The generated report output is empty.";
            DomainServiceException dse = new DomainServiceException(msg);
            LOG.throwing(CLASSNAME, methodName, dse);
            throw dse;
        }

        final StudentTranscriptReport transcriptReport = new StudentTranscriptReportImpl(
                content, reportFormat, filename, "Transcript"
        );
        LOG.log(Level.FINE, "Created StudentTranscriptReport {0} for student {1}.", new Object[]{transcriptReport, student.getPen()});

        LOG.exiting(CLASSNAME, methodName);
        return transcriptReport;
    }

    @Override
    @RolesAllowed({FULFILLMENT_SERVICES_USER})
    public Parameters<String, Object> createParameters() {
        final String methodName = "createParameters()";
        LOG.entering(CLASSNAME, methodName);

        Parameters<String, Object> parameters = reportService.createParameters();

        LOG.exiting(CLASSNAME, methodName);
        return parameters;
    }

    @Override
    GraduationReport createGraduationReport() {
        throw new NotImplementedException("Method createGraduationReport() not implemented");
    }

    private StudentTranscriptReport getStudentTranscriptReport(
            final PersonalEducationNumber personalEducationNumber,
            final ReportFormat format,
            final boolean preview,
            final Parameters<String, Object> parameters) throws DomainServiceException, IOException {
        final String methodName = "getStudentTranscriptReport(String, ReportFormat, boolean, Parameters)";
        LOG.entering(CLASSNAME, methodName);
        final String pen = personalEducationNumber.getValue();
        final StudentInfo studentInfo = getStudentInfo(pen);

        // Adapt TRAX data to other objects for reporting.
        final String programCode = studentInfo.getGradReqYear();
        final String logo = studentInfo.getLogo();
        final Transcript transcript = getTranscript(pen);

        final Student student = adaptStudent(personalEducationNumber, studentInfo);
        final School school = adaptSchool(studentInfo, getAccessToken(), true);

        final GradProgram program = adapt(school.getSchoolCategoryCode(), programCode, transcript.getTranscriptTypeCode(), getAccessToken());

        final GraduationData graduationData = adaptGraduationData(studentInfo, transcript);

        final String gradMessage = studentInfo.getGradMessage();
        final List<NonGradReason> nonGradReasons = adaptReasons(studentInfo);

        final StudentTranscriptReport report = createReport(
                format,
                preview,
                student,
                school,
                logo,
                transcript,
                program,
                nonGradReasons,
                gradMessage,
                transcript.getIssueDate(),
                parameters,
                graduationData
        );

        LOG.exiting(CLASSNAME, methodName);
        return report;
    }

    private String getCreditsUsedForGrad(final Transcript transcript) {
        final List<TranscriptResult> results = transcript.getResults();
        int totalCredits = 0;

        for (final TranscriptResult transcriptResult : results) {
            final String credits = nullSafe(transcriptResult.getUsedForGrad());
            totalCredits += parseCredits(credits);
        }

        return "" + totalCredits;
    }

    // FIXME: Pass in GraduationProgramCode enum
    private GraduationData adaptGraduationData(
            final StudentInfo studentInfo,
            final Transcript transcript) {
        final String methodName = "adaptGraduationData(StudentInfo, Transcript, String)";
        final Object[] params = {studentInfo, transcript};
        LOG.entering(CLASSNAME, methodName, params);

        final GraduationData graduationData = new GraduationDataImpl();

        Date gradDate = studentInfo.getGradDate();

        ((GraduationDataImpl) graduationData).setGraduationDate(gradDate);
        ((GraduationDataImpl) graduationData).setHonorsFlag(studentInfo.isHonourFlag());
        ((GraduationDataImpl) graduationData).setDogwoodFlag(studentInfo.isDogwoodFlag());
        ((GraduationDataImpl) graduationData).setProgramNames(studentInfo.getAcademicProgram());
        final String creditsUsedForGrad = getCreditsUsedForGrad(transcript);
        ((GraduationDataImpl) graduationData).setTotalCreditsUsedForGrad(creditsUsedForGrad);

        LOG.exiting(CLASSNAME, methodName);

        return graduationData;
    }

    /**
     * Ensure that the student's highest mark for a particular course is used.
     * This will remove any duplicate courses that may be present in favour of
     * the highest marked course.
     *
     * @param results Courses for PEN user which might have duplicated courses
     * @return
     */
    private List<TranscriptCourse> filterCourses(final List<TranscriptCourse> results) {

        final List<TranscriptCourse> resultOfCourses = new ArrayList<>();
        for (final TranscriptCourse course : results) {

            if (!resultOfCourses.contains(course)) {
                final TranscriptCourse interimCourse
                        = getInterimCourse(course, results);

                if (!(resultOfCourses.contains(interimCourse))) {
                    resultOfCourses.add(interimCourse);
                }
            }
        }

        return resultOfCourses;
    }

    /**
     * If the in progress course is a duplicate of a successfully complete
     * course (i.e. the course already appears on the student's transcript with
     * a passing final mark), the in progress course replaces the successfully
     * completed occurrence of the course if and only if the interim percent is
     * greater than the final percent on the successfully completed occurrence
     * of the course. If the interim percent is blank it should not replace the
     * successfully completed occurrence of the course.
     */
    private TranscriptCourse getInterimCourse(
            TranscriptCourse course,
            final List<TranscriptCourse> results) {
        //Check for dulicate courses
        for (final TranscriptCourse compareCourse : results) {
            //Check and compare two courses for duplication and if required
            //replace course based on requirement.
            if (course.courseEquals(compareCourse)
                    && course.compareCourse(compareCourse)) {
                course = compareCourse;
            }
        }
        return course;

    }

    /**
     * @param results
     * @param code
     * @inheritDoc
     */
    @RolesAllowed({USER, FULFILLMENT_SERVICES_USER})
    @Override
    public List<TranscriptResult> sort(
            final List<TranscriptResult> results,
            final GraduationProgramCode code) {

        // Perform multiple stable sorts over the transcript results.
        final Comparator<TranscriptResult> comparator = createComparator(code);
        Collections.sort(results, comparator);

        // Sort the ungraded courses to the end of the list, which will then
        // be pushed up using the assessment comparator.
        final Comparator<TranscriptResult> ungraded = createUngradedComparator();
        Collections.sort(results, ungraded);

        // Sort the ReportCourseType.ASSESSMENT values to the end of the
        // list. This could use a comparator chain.
        final Comparator<TranscriptResult> assessments = createAssessmentComparator();
        Collections.sort(results, assessments);

        return results;
    }

    /**
     * The sort order for the courses is as follows:
     *
     * For the 1986 and Adult transcript, the courses are sorted only by course
     * code. For the 2004, 1995, and SCCP transcript, the courses are sorted by
     * course level and then by course name.
     *
     * @param code Program code that influences sort order.
     */
    private Comparator<TranscriptResult> createComparator(
            final GraduationProgramCode code) {
        final Comparator<TranscriptResult> result;

        switch (code) {
            case PROGRAM_1950:
            case PROGRAM_1986:
            // 1995, 2004, 2018, etc.
            default:
                result = createRegularComparator();
                break;
        }

        return result;
    }

    /**
     * Returns a comparator that can sort by course code.
     *
     * @return A comparator for sorting by course code.
     */
    private Comparator<TranscriptResult> createAdultComparator() {
        return new Comparator<TranscriptResult>() {
            @Override
            public int compare(
                    final TranscriptResult tr1,
                    final TranscriptResult tr2) {
                final String reportCourseType1 = getReportCourseType(tr1);
                final String reportCourseType2 = getReportCourseType(tr2);
                final String code1 = getCourseCode(tr1);
                final String code2 = getCourseCode(tr2);

                return new CompareToBuilder()
                        //.append(reportCourseType1, reportCourseType2)
                        .append(code1, code2)
                        .toComparison();
            }
        };
    }

    /**
     * Called for non-Adult reports to provide comparators that can perform
     * stable sub-sorts on the transcript results.
     *
     * @return A list of stable comparators that should be executed in order to
     * sort the transcript results.
     */
    private Comparator<TranscriptResult> createRegularComparator() {
        return new Comparator<TranscriptResult>() {
            @Override
            public int compare(final TranscriptResult tr1, final TranscriptResult tr2) {
                final int level1 = getCourseLevel(tr1);
                final int level2 = getCourseLevel(tr2);
                final String name1 = getCourseName(tr1);
                final String name2 = getCourseName(tr2);

                return new CompareToBuilder()
                        .append(level1, level2)
                        .append(name1, name2)
                        .toComparison();
            }
        };
    }

    /**
     * Sorts ungraded to the bottom of the list of transcript results.
     *
     * @return A comparator that can sort ungraded results.
     */
    private Comparator<TranscriptResult> createUngradedComparator() {
        return new Comparator<TranscriptResult>() {
            @Override
            public int compare(final TranscriptResult tr1, final TranscriptResult tr2) {
                final int level1 = getCourseLevel(tr1);
                final int level2 = getCourseLevel(tr2);

                final int comparison = new CompareToBuilder()
                        .append(level1, level2)
                        .toComparison();

                return SORT_UNGRADED.equals("" + level1)
                        || SORT_UNGRADED.equals("" + level2)
                                ? comparison
                                : 0;

            }
        };
    }

    /**
     * Used to sort assessments to the bottom of the list of transcript results.
     *
     * @return A comparator that can sort assessment results.
     */
    private Comparator<TranscriptResult> createAssessmentComparator() {
        return new Comparator<TranscriptResult>() {
            @Override
            public int compare(final TranscriptResult tr1, final TranscriptResult tr2) {
                final int level1 = getCourseLevel(tr1);
                final int level2 = getCourseLevel(tr2);

                final String reportCourseType1 = getReportCourseType(tr1);
                final String reportCourseType2 = getReportCourseType(tr2);

                final String courseCode1 = getCourseCode(tr1);
                final String courseCode2 = getCourseCode(tr2);

                final int comparison = new CompareToBuilder()
                        .append(level1, level2)
                        .append(reportCourseType1, reportCourseType2)
                        .append(courseCode1, courseCode2)
                        .toComparison();

                return ASSESSMENT.isCode(reportCourseType1)
                        || ASSESSMENT.isCode(reportCourseType2)
                                ? comparison
                                : 0;
            }
        };
    }

    /**
     * Convenience method to obtain a sortable course type.
     *
     * @param tr The transcript result containing report course type that
     * control sort order.
     * @return The report course type for the given transcript result.
     */
    private String getReportCourseType(final TranscriptResult tr) {
        final Course c = tr.getCourse();
        final String reportCourseType = c == null
                ? PROVINCIALLY_EXAMINABLE.getCode()
                : c.getType();

        return reportCourseType;
    }

    /**
     * Convenience method to obtain a sortable course level.
     *
     * @param tr The transcript result containing course levels to be sorted.
     * @return The course level or "99" if the course has no level (and should
     * therefore be sorted to the bottom).
     */
    private int getCourseLevel(final TranscriptResult tr) {
        final ca.bc.gov.educ.grad.report.model.transcript.Course c = tr.getCourse();
        final String cl = c == null ? "" : c.getLevel().trim();
        final String type = c == null ? "" : c.getType();

        final String level = ASSESSMENT.isCode(type)
                ? SORT_ASSESSMENT
                : SORT_UNGRADED;
        final String courseLevel = cl.isEmpty() ? level : cl;
        int result = 0;

        try {
            // Parse "12A" to 12, "11F" to 11, "10" to 10, for sort purposes.
            final NumberFormat nf = getIntegerInstance();
            result = nf.parse(courseLevel).intValue();
        } catch (final Exception ex) {
            LOG.log(Level.SEVERE,
                    "Could not parse course level into integer: " + courseLevel,
                    ex);
        }

        return result;
    }

    /**
     * Convenience method to obtain a sortable course name.
     *
     * @param tr The transcript result containing course names to be sorted.
     * @return The course name, never null, possibly empty.
     */
    private String getCourseName(final TranscriptResult tr) {
        final Course c = tr.getCourse();
        final String name = c == null ? "" : c.getName();

        return nullSafe(name);
    }

    /**
     * Convenience method to obtain a sortable course name.
     *
     * @param tr The transcript result containing course names to be sorted.
     * @return The course name, never null, possibly empty.
     */
    private String getCourseCode(final TranscriptResult tr) {
        final Course c = tr.getCourse();
        final String code = c == null ? "" : c.getCode();

        return nullSafe(code);
    }
}
