/*
 * *********************************************************************
 *  Copyright (c) 2017, Ministry of Education, BC.
 *
 *  All rights reserved.
 *    This information contained herein may not be used in whole
 *    or in part without the express written consent of the
 *    Government of British Columbia, Canada.
 *
 *  Revision Control Information
 *  File:                $Id::                                                 $
 *  Date of Last Commit: $Date::                                               $
 *  Revision Number:     $Rev::                                                $
 *  Last Commit by:      $Author::                                             $
 *
 * ***********************************************************************
 */
package ca.bc.gov.educ.grad.report.service.impl;

import ca.bc.gov.educ.grad.report.api.client.ReportData;
import ca.bc.gov.educ.grad.report.dao.GradDataConvertionBean;
import ca.bc.gov.educ.grad.report.dao.ReportRequestDataThreadLocal;
import ca.bc.gov.educ.grad.report.dto.SignatureBlockTypeCode;
import ca.bc.gov.educ.grad.report.dto.impl.*;
import ca.bc.gov.educ.grad.report.dto.reports.impl.ParametersImpl;
import ca.bc.gov.educ.grad.report.exception.EntityNotFoundException;
import ca.bc.gov.educ.grad.report.model.achievement.*;
import ca.bc.gov.educ.grad.report.model.assessment.AssessmentResult;
import ca.bc.gov.educ.grad.report.model.common.DataException;
import ca.bc.gov.educ.grad.report.model.common.DomainServiceException;
import ca.bc.gov.educ.grad.report.model.common.SignatureBlockType;
import ca.bc.gov.educ.grad.report.model.graduation.*;
import ca.bc.gov.educ.grad.report.model.reports.*;
import ca.bc.gov.educ.grad.report.model.school.School;
import ca.bc.gov.educ.grad.report.model.student.PersonalEducationNumber;
import ca.bc.gov.educ.grad.report.model.student.Student;
import ca.bc.gov.educ.grad.report.model.student.StudentInfo;
import ca.bc.gov.educ.grad.report.model.transcript.Course;
import ca.bc.gov.educ.grad.report.model.transcript.GraduationData;
import ca.bc.gov.educ.grad.report.service.GradReportCodeService;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang3.builder.CompareToBuilder;
import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.AsyncResult;
import org.springframework.stereotype.Service;

import javax.annotation.security.DeclareRoles;
import javax.annotation.security.RolesAllowed;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.net.URL;
import java.text.NumberFormat;
import java.util.*;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;

import static ca.bc.gov.educ.grad.report.dto.impl.constants.Roles.STUDENT_ACHIEVEMENT_REPORT;
import static ca.bc.gov.educ.grad.report.model.common.support.VerifyUtils.nullSafe;
import static ca.bc.gov.educ.grad.report.model.common.support.impl.Roles.FULFILLMENT_SERVICES_USER;
import static ca.bc.gov.educ.grad.report.model.common.support.impl.Roles.USER;
import static ca.bc.gov.educ.grad.report.model.course.ReportCourseType.ASSESSMENT;
import static ca.bc.gov.educ.grad.report.model.course.ReportCourseType.PROVINCIALLY_EXAMINABLE;
import static ca.bc.gov.educ.grad.report.model.reports.ReportFormat.PDF;
import static java.lang.Integer.parseInt;
import static java.text.NumberFormat.getIntegerInstance;
import static org.apache.commons.lang3.ArrayUtils.isEmpty;

/**
 * The achievement service is an implementation component of the broader
 * Achievement Services group. As part of the mid-tier service layer the
 * buildReport method called by the GUI (browser) to display the unofficial
 * achievement of grades. The display is a rendered report generated by the
 * report service populated with data from the TRAX adaptor for the current user
 * as determined by the student demographics service.
 * <p>
 * This service integrates with the Student Demographics, the TRAX adaptor, and
 * the Reporting Service.
 * </p>
 * <p>
 * The security roles required to build a achievement report are:
 * <ol>
 * <li>XS_REPORT</li>
 * <li>TRAX_READ</li>
 * <li>SXR_READ</li>
 * <li>SXR_SEARCH</li>
 * <li>USER_REPORTS_EXPORT</li>
 * <li>USER_REPORTS_TRANSCRIPT</li>
 * <li>USER_PROFILE_SEARCH</li>
 * <li>USER_PROFILE_READ</li>
 * <li>USER</li>
 * </ol>
 *
 * @author CGI Information Management Consultants Inc.
 */
@Service
@DeclareRoles({STUDENT_ACHIEVEMENT_REPORT, USER, FULFILLMENT_SERVICES_USER})
public class StudentAchievementServiceImpl implements StudentAchievementService, Serializable {

    private static final long serialVersionUID = 5L;

    private static final String CLASSNAME = StudentAchievementServiceImpl.class.getName();
    private static final Logger LOG = Logger.getLogger(CLASSNAME);

    /**
     * Sort order for ungraded courses (to bottom, above assessments).
     */
    private static final String SORT_UNGRADED = "99";

    /**
     * Sort order for assessments (to bottom, below ungraded).
     */
    private static final String SORT_ASSESSMENT = "100";

    private final String FORMAT_COURSE_CODE = "%-5s";
    private final String FORMAT_COURSE_LEVEL = "%-3s";
    private static final String DIR_IMAGE_BASE = "/reports/resources/images/";

    @Autowired
    private ReportService reportService;
    @Autowired
    private GradReportCodeService codeService;

    @Autowired
    GradDataConvertionBean gradDataConvertionBean;

    /**
     * Creates the student's official achievement as a PDF (no other formats are
     * allowed for official achievements).
     *
     * @return A filled achievement report suitable for sending to a PSI.
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    @Override
    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public StudentAchievementReport buildOfficialAchievementReport()
            throws DomainServiceException, IOException, DataException {
        return createAchievementReport(PDF, false, false);
    }

    /**
     * Builds an unofficial achievement report.
     *
     * @param format PDF, HTML, etc.
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    @Override
    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public StudentAchievementReport buildAchievementReport(
            final ReportFormat format)
            throws DomainServiceException, IOException, DataException {
        return buildAchievementReport(format, false);
    }

    /**
     * Builds an unofficial achievement report.
     *
     * @param format PDF, HTML, etc.
     * @param pen    student identifier.
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    @Override
    @RolesAllowed({FULFILLMENT_SERVICES_USER})
    public StudentAchievementReport buildAchievementReport(
            final ReportFormat format, final PersonalEducationNumber pen, final Parameters parameters, final boolean interim)
            throws DomainServiceException, IOException, DataException {
        return createAchievementReport(format, true, pen, parameters, interim);
    }

    /**
     * Builds an unofficial achievement report asynchronously. Calls
     * <code>createAchievementReport(ReportFormat, true)</code> and returns the
     * result wrapped in an AsyncResult.
     *
     * @param format PDF, HTML, etc.
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    @Override
    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public Future<StudentAchievementReport> buildAchievementReportAsync(
            final ReportFormat format)
            throws DomainServiceException, IOException, DataException {
        return new AsyncResult<>(createAchievementReport(format, true, false));
    }

    private GradProgram createGradProgram(String code) {
        if (StringUtils.trimToNull(code) == null) {
            code = GraduationProgramCode.PROGRAM_2018.getCode();
        }
        return new GradProgramImpl(GraduationProgramCode.valueFrom(code));
    }

    /**
     * Creates a report in a specific format, either official or unofficial,
     * depending on the preview value.
     *
     * @param format
     * @param preview Set to false to create an unofficial achievement
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    private StudentAchievementReport createAchievementReport(
            final ReportFormat format,
            final boolean preview, final boolean interim)
            throws DomainServiceException, IOException, DataException {
        final String _m = "createAchievement(ReportFormat, boolean)";
        LOG.entering(CLASSNAME, _m);

        final PersonalEducationNumber pen = getStudentPEN();
        LOG.log(Level.FINE, "Retrieved studentInfo for pen: {0}.", pen.getValue());

        final StudentAchievementReport report = getStudentAchievementReport(
                pen, format, preview, null, interim
        );
        LOG.exiting(CLASSNAME, _m);
        return report;
    }

    /**
     * Creates a report in a specific format, either official or unofficial,
     * depending on the preview value. Takes the PEN to generate the desired
     * report.
     *
     * @param format
     * @param preview Set to false to create an unofficial achievement
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    private StudentAchievementReport createAchievementReport(
            final ReportFormat format,
            final boolean preview, final PersonalEducationNumber pen, final Parameters parameters, final boolean interim)
            throws DomainServiceException, IOException, DataException {
        final String _m = "createAchievement(ReportFormat, boolean)";
        LOG.entering(CLASSNAME, _m);
        LOG.log(Level.FINE, "Retrieved achievement for pen: {0}.", pen.getValue());

        final StudentAchievementReport report = getStudentAchievementReport(pen, format, preview, parameters, interim);
        LOG.log(Level.INFO, "Created StudentAchievementReport for pen: {0}.", pen.getValue());

        LOG.exiting(CLASSNAME, _m);
        return report;
    }

    private PersonalEducationNumber getStudentPEN() throws DomainServiceException {
        final String _m = "getStudentPEN()";
        LOG.entering(CLASSNAME, _m);

        ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

        if (reportData == null) {
            EntityNotFoundException dse = new EntityNotFoundException(
                    null,
                    "Report Data not exists for the current report generation");
            LOG.throwing(CLASSNAME, _m, dse);
            throw dse;
        }

        PersonalEducationNumberObject pen = new PersonalEducationNumberObject();
        pen.setPen(reportData.getStudent().getPen().getPen());

        LOG.log(Level.FINE, "Confirmed the user is a student and retrieved the PEN: {0}.", pen);
        LOG.exiting(CLASSNAME, _m);
        return pen;
    }

    /**
     * Read the static student data from TRAX which is needed for the achievement
     * service.
     *
     * @param pen
     * @return
     */
    private StudentInfo getStudentInfo(final String pen) throws DataException, DomainServiceException {
        final String _m = "getStudentInfo(String)";
        LOG.entering(CLASSNAME, _m);

        final StudentInfo studentInfo;

        try {

            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        null,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, _m, dse);
                throw dse;
            }

            StudentInfoImpl student = (StudentInfoImpl) gradDataConvertionBean.getStudentInfo(reportData);
            final HashMap<String, String> reasons = gradDataConvertionBean.getNongradReasons(reportData);
            student.setNonGradReasons(reasons);
            studentInfo = student;

            LOG.log(Level.FINER,
                    "Retrieved student info from TRAX for PEN: {0}", pen);

            if (studentInfo == null) {
                final String msg = "Failed to find achievement results in TRAX for PEN: ".concat(pen);
                final DomainServiceException dse = new DomainServiceException(null, msg);
                LOG.throwing(CLASSNAME, _m, dse);
                throw dse;
            } else {
                LOG.log(Level.FINEST, "Retrieved student from achievement:");
                LOG.log(Level.FINEST, "{0} {1} {2}",
                        new Object[]{studentInfo.getPen(), studentInfo.getFirstName(), studentInfo.getLastName()});
            }

        } catch (Exception ex) {
            String msg = "Failed to access TRAX achievement data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, _m, dex);
            throw dex;
        }

        LOG.log(Level.FINE, "Completed call to TRAX.");
        LOG.exiting(CLASSNAME, _m);
        return studentInfo;
    }

    /**
     * Read the collection of achievement courses from the TRAX Adaptor which is
     * required for the achievement service.
     *
     * @param pen Student identifier.
     * @return
     */
    private List<AchievementCourse> getAchievementCourseList(
            final String pen, final boolean interim)
            throws DataException, DomainServiceException {
        final String m_ = "getAchievementCourseList(String, boolean)";
        LOG.entering(CLASSNAME, m_);

        final List<AchievementCourse> results;

        try {

            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        null,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, m_, dse);
                throw dse;
            }

            results = gradDataConvertionBean.getAchievementCourses(reportData);

            LOG.log(Level.INFO,
                    "Retrieved the collection of exam results from TRAX for PEN: {0} INTERIM: {1}",
                    new Object[]{pen, interim});

            if (results != null && !results.isEmpty()) {
                LOG.log(Level.INFO,
                        "Total courses {0} retrieved  for PEN: {1}",
                        new Object[]{results.size(), pen});
                LOG.log(Level.FINEST, "Retrieved student achievement course results:");
                for (AchievementCourse result : results) {
                    LOG.log(Level.FINEST, "{0} {1}",
                            new Object[]{result.getCourseName(), result.getFinalLetterGrade()});
                }
            }
        } catch (final Exception ex) {
            String msg = "Failed to access TRAX achievement course data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, m_, dex);
            throw dex;
        }

        LOG.log(Level.FINE, "Completed call to TRAX.");
        LOG.exiting(CLASSNAME, m_);
        return results;
    }

    /**
     * Read the collection of achievement courses from the Adaptor which is
     * required for the achievement service.
     *
     * @param pen Student identifier.
     * @return
     */
    private List<AssessmentResult> getAssessmentResultList(
            final String pen)
            throws DataException, DomainServiceException {
        final String m_ = "getAssessmentList(String, boolean)";
        LOG.entering(CLASSNAME, m_);

        final List<AssessmentResult> results;

        try {
            LOG.log(Level.INFO,
                    "Retrieved the collection of exam results from TRAX for PEN: {0}",
                    new Object[]{pen});

            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        null,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, m_, dse);
                throw dse;
            }

            List<AssessmentResult> resultsList = gradDataConvertionBean.getAssessmentCourses(reportData);
            results = new ArrayList<>();
            for (AssessmentResult course : resultsList) {
                results.add(course);
            }

            if (results != null && !results.isEmpty()) {
                LOG.log(Level.INFO,
                        "Total courses {0} retrieved  for PEN: {1}",
                        new Object[]{results.size(), pen});
                LOG.log(Level.FINEST, "Retrieved student achievement course results:");
                for (AssessmentResult result : results) {
                    LOG.log(Level.FINEST, "{0} {1}",
                            new Object[]{result.getAssessmentCode(), result.getProficiencyScore()});
                }
            }
        } catch (final Exception ex) {
            String msg = "Failed to access TRAX achievement course data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, m_, dex);
            throw dex;
        }

        LOG.log(Level.FINE, "Completed call to TRAX.");
        LOG.exiting(CLASSNAME, m_);
        return results;
    }

    /**
     * Read the collection of achievement courses from the Adaptor which is
     * required for the achievement service.
     *
     * @param pen Student identifier.
     * @return
     */
    private GraduationStatus getGraduationStatus(
            final String pen)
            throws DataException, DomainServiceException {
        final String m_ = "getAssessmentList(String, boolean)";
        LOG.entering(CLASSNAME, m_);

        final GraduationStatus result;

        try {
            LOG.log(Level.INFO,
                    "Retrieved the collection of exam results from TRAX for PEN: {0}",
                    new Object[]{pen});

            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        null,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, m_, dse);
                throw dse;
            }

            result = new GraduationStatusImpl();
            BeanUtils.copyProperties(reportData.getGraduationStatus(), result);

        } catch (final Exception ex) {
            String msg = "Failed to access TRAX achievement course data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, m_, dex);
            throw dex;
        }

        LOG.log(Level.FINE, "Completed call to TRAX.");
        LOG.exiting(CLASSNAME, m_);
        return result;
    }

    /**
     * Read the collection of student exams from the Adaptor which is
     * required for the achievement service.
     *
     * @param pen Student identifier.
     * @return
     */
    private List<Exam> getStudentExamList(
            final String pen)
            throws DataException, DomainServiceException {
        final String m_ = "getAssessmentList(String, boolean)";
        LOG.entering(CLASSNAME, m_);

        final List<Exam> results;

        try {
            LOG.log(Level.INFO,
                    "Retrieved the collection of exam results from TRAX for PEN: {0}",
                    new Object[]{pen});

            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        null,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, m_, dse);
                throw dse;
            }

            List<Exam> resultsList = gradDataConvertionBean.getStudentExams(reportData);
            results = new ArrayList<>();
            for (Exam exam : resultsList) {
                results.add(exam);
            }

            if (results != null && !results.isEmpty()) {
                LOG.log(Level.INFO,
                        "Total exam {0} retrieved  for PEN: {1}",
                        new Object[]{results.size(), pen});
                LOG.log(Level.FINEST, "Retrieved student exam results:");
                for (Exam result : results) {
                    LOG.log(Level.FINEST, "{0} {1}",
                            new Object[]{result.getCourseCode(), result.getBestExamPercent()});
                }
            }
        } catch (final Exception ex) {
            String msg = "Failed to access exam data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, m_, dex);
            throw dex;
        }

        LOG.log(Level.FINE, "Completed call to TRAX.");
        LOG.exiting(CLASSNAME, m_);
        return results;
    }

    /**
     * Read the collection of student exams from the Adaptor which is
     * required for the achievement service.
     *
     * @param pen Student identifier.
     * @return
     */
    private List<OptionalProgram> getOptionalProgramList(
            final String pen)
            throws DataException, DomainServiceException {
        final String m_ = "getOptionalProgramList(String)";
        LOG.entering(CLASSNAME, m_);

        final List<OptionalProgram> results;

        try {
            LOG.log(Level.INFO,
                    "Retrieved the collection of exam results from TRAX for PEN: {0}",
                    new Object[]{pen});

            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        null,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, m_, dse);
                throw dse;
            }

            List<OptionalProgram> resultsList = gradDataConvertionBean.getOptionalPrograms(reportData);
            results = new ArrayList<>();
            for (OptionalProgram exam : resultsList) {
                results.add(exam);
            }

            if (results != null && !results.isEmpty()) {
                LOG.log(Level.INFO,
                        "Total exam {0} retrieved  for PEN: {1}",
                        new Object[]{results.size(), pen});
                LOG.log(Level.FINEST, "Retrieved student exam results:");
                for (OptionalProgram result : results) {
                    LOG.log(Level.FINEST, "{0} {1}",
                            new Object[]{result.getOptionalProgramCode(), result.getOptionalProgramName()});
                }
            }
        } catch (final Exception ex) {
            String msg = "Failed to access optional Program data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, m_, dex);
            throw dex;
        }

        LOG.log(Level.FINE, "Completed call to TRAX.");
        LOG.exiting(CLASSNAME, m_);
        return results;
    }

    /**
     * Adapt the TRAX data from the data value object into a Student object.
     *
     * @param pen
     * @param studentInfo
     */
    private Student adaptStudent(
            final PersonalEducationNumber pen,
            final StudentInfo studentInfo) {

        final String _m = "adaptStudent(PersonalEducationNumber, StudentInfo)";
        final Object[] params = {pen, studentInfo};
        LOG.entering(CLASSNAME, _m, params);

        final StudentImpl student = new StudentImpl();
        student.setPen(pen);
        student.setFirstName(studentInfo.getFirstName());
        student.setMiddleName(studentInfo.getMiddleName());
        student.setLastName(studentInfo.getLastName());
        student.setBirthdate(studentInfo.getBirthdate());
        student.setGrade(studentInfo.getGrade());
        student.setGender(studentInfo.getGender());
        student.setHasOtherProgram(studentInfo.getHasOtherProgram());
        student.setGradProgram(studentInfo.getGradProgram());
        student.setOtherProgramParticipation(studentInfo.getOtherProgramParticipation());

        final PostalAddressImpl address = new PostalAddressImpl();
        address.setStreetLine1(studentInfo.getStudentAddress1());
        address.setStreetLine2(studentInfo.getStudentAddress2());
        address.setCity(studentInfo.getStudentCity());
        address.setCode(studentInfo.getStudentPostalCode());
        address.setRegion(studentInfo.getStudentProv());
        address.setCountry(studentInfo.getCountryCode());
        student.setCurrentMailingAddress(address);

        final Map<String, SignatureBlockTypeCode> signatureBlockTypeCodes = codeService.getSignatureBlockTypeCodesMap();
        final Map<String, SignatureBlockType> signatureBlockTypes = new HashMap<>();
        signatureBlockTypes.putAll(signatureBlockTypeCodes);
        student.setSignatureBlockTypes(signatureBlockTypes);

        LOG.exiting(CLASSNAME, _m);
        return student;
    }

    /**
     * Adapt the TRAX data from the data value object into a School object.
     *
     * @param studentInfo
     */
    private School adaptSchool(final StudentInfo studentInfo) {
        final String m_ = "adaptSchool(StudentInfo)";
        LOG.entering(CLASSNAME, m_, studentInfo);

        final SchoolImpl school = new SchoolImpl();
        school.setMincode(studentInfo.getMincode());
        school.setName(studentInfo.getSchoolName());
        school.setTypeIndicator(studentInfo.getSchoolTypeIndicator());
        school.setTypeBanner(studentInfo.getSchoolTypeBanner());

        final CanadianPostalAddressImpl address = new CanadianPostalAddressImpl();
        address.setStreet1(studentInfo.getSchoolStreet());
        address.setStreet2(studentInfo.getSchoolStreet2());
        address.setCity(studentInfo.getSchoolCity());
        address.setPostalCode(studentInfo.getSchoolPostalCode());
        address.setProvince(studentInfo.getSchoolProv());
        school.setAddress(address);

        LOG.exiting(CLASSNAME, m_);
        return school;
    }

    /**
     * Convert non-graduation reasons from a TRAX map to an STs list.
     *
     * @param student The student instance that has non-grad reasons to
     *                convert.
     * @return The map of non-grad reasons converted from a map to a list of
     * NonGradReasons instances.
     */
    private List<NonGradReason> adaptReasons(final StudentInfo student) {
        final String _m = "adaptReasons(StudentInfo)";
        LOG.entering(CLASSNAME, _m);

        final Map<String, String> gradReasons = student.getNonGradReasons();
        final List<NonGradReason> reasons = new ArrayList<>();

        for (Map.Entry<String, String> entry : gradReasons.entrySet()) {
            final String key = entry.getKey();
            final String value = entry.getValue();
            NonGradReasonImpl r = new NonGradReasonImpl();
            r.setCode(key);
            r.setDescription(value);
            reasons.add(r);
        }

        LOG.exiting(CLASSNAME, _m);
        return reasons;
    }

    /**
     * Create an unofficial achievement of grades report.
     *
     * @param reportFormat
     * @param preview
     * @return
     * @throws DomainServiceException
     */
    private synchronized StudentAchievementReport createReport(
            final ReportFormat reportFormat,
            final boolean preview,
            final Parameters parameters,
            final boolean interim,
            final String gradProgram) throws DomainServiceException, IOException {
        final String _m = "createReport(...)";
        LOG.entering(CLASSNAME, _m);

        final AchievementReport report = reportService.createAchievementReport();

        if (parameters != null) {
            report.setParameters(parameters);
        }

        // Indicate official/unofficial
        report.setPreview(preview);
        report.setFormat(reportFormat);
        report.setInterim(interim);
        report.setGraduationProgram(createGradProgram(gradProgram));

        final ReportDocument document;

        try {
            document = reportService.export(report);
        } catch (final Exception ex) {
            final String msg = "Failed to create report.";
            LOG.log(Level.SEVERE, msg, ex);
            final DomainServiceException dse = new DomainServiceException(msg, ex);
            LOG.throwing(CLASSNAME, _m, dse);
            throw dse;
        }

        final String filename = report.getFilename();
        final byte[] content = document.asBytes();

        if (isEmpty(content)) {
            final String msg = "The generated report output is empty.";
            DomainServiceException dse = new DomainServiceException(msg);
            LOG.throwing(CLASSNAME, _m, dse);
            throw dse;
        }

        final StudentAchievementReport achievementReport = new StudentAchievementReportImpl(
                content, reportFormat, filename, "Achievement"
        );
        LOG.log(Level.FINE, "Created StudentAchievementReport {0}.", new Object[]{achievementReport});

        LOG.exiting(CLASSNAME, _m);
        return achievementReport;
    }

    @Override
    @RolesAllowed({FULFILLMENT_SERVICES_USER})
    public Parameters createParameters() {
        final String _m = "createParameters()";
        LOG.entering(CLASSNAME, _m);

        Parameters parameters = reportService.createParameters();

        LOG.exiting(CLASSNAME, _m);
        return parameters;
    }

    private StudentAchievementReport getStudentAchievementReport(
            final PersonalEducationNumber personalEducationNumber,
            final ReportFormat format,
            final boolean preview,
            Parameters parameters,
            final boolean interim) throws DomainServiceException, IOException {
        final String _m = "getStudentAchievementReport(String, ReportFormat, boolean, Parameters, boolean)";
        LOG.entering(CLASSNAME, _m);

        if (parameters == null) {
            parameters = new ParametersImpl();
        }

        String pen = personalEducationNumber.getPen();
        StudentInfo studentInfo = getStudentInfo(personalEducationNumber.getPen());

        List<Exam> sExamObjList = getStudentExamList(pen);
        parameters.put("hasStudentExam", "false");
        if (!sExamObjList.isEmpty()) {
            JRBeanCollectionDataSource jrBeanCollectionDataSource = new JRBeanCollectionDataSource(sExamObjList);
            parameters.put("studentExam", jrBeanCollectionDataSource);
            parameters.put("hasStudentExam", "true");
        }

        List<AchievementCourse> sCourseObjList = getAchievementCourseList(pen, interim);
        parameters.put("hasStudentCourse", "false");
        if (!sCourseObjList.isEmpty()) {
            JRBeanCollectionDataSource jrBeanCollectionDataSource = new JRBeanCollectionDataSource(sCourseObjList);
            parameters.put("studentCourse", jrBeanCollectionDataSource);
            parameters.put("hasStudentCourse", "true");
        }

        List<AssessmentResult> sAssessmentObjList = this.getAssessmentResultList(pen);
        parameters.put("hasStudentAssessment", "false");
        if (!sAssessmentObjList.isEmpty()) {
            JRBeanCollectionDataSource jrBeanCollectionDataSource = new JRBeanCollectionDataSource(sAssessmentObjList);
            parameters.put("studentAssessment", jrBeanCollectionDataSource);
            parameters.put("hasStudentAssessment", "true");
        }

        List<ca.bc.gov.educ.grad.report.model.graduation.NonGradReason> nongradList = adaptReasons(studentInfo);
        parameters.put("hasNonGradReasons", "false");
        if (!nongradList.isEmpty()) {
            JRBeanCollectionDataSource jrBeanCollectionDataSource = new JRBeanCollectionDataSource(nongradList);
            parameters.put("nonGradReason", jrBeanCollectionDataSource);
            parameters.put("hasNonGradReasons", "true");
        }

        List<OptionalProgram> optionalProgramList = this.getOptionalProgramList(pen);
        parameters.put("hasOptionalPrograms", "false");
        if (!optionalProgramList.isEmpty()) {
            JRBeanCollectionDataSource jrBeanCollectionDataSource = new JRBeanCollectionDataSource(optionalProgramList);
            parameters.put("optionalProgram", jrBeanCollectionDataSource);
            parameters.put("hasOptionalPrograms", "true");
        }


        ca.bc.gov.educ.grad.report.model.school.School schoolObj = adaptSchool(studentInfo);
        if (schoolObj != null) {
            parameters.put("schoolObj", schoolObj);
        }

        ca.bc.gov.educ.grad.report.model.student.Student studentObj = adaptStudent(personalEducationNumber, studentInfo);
        if (studentObj != null) {
            parameters.put("studentObj", studentObj);
        }

        GraduationStatus graduationStatus = getGraduationStatus(pen);
        if (graduationStatus != null) {
            parameters.put("gradObj", graduationStatus);
        }

        InputStream inputLogo = openImageResource("logo_" + studentInfo.getLogo().toLowerCase(Locale.ROOT) + ".svg");
        parameters.put("orgImage", inputLogo);

        final StudentAchievementReport report = createReport(
                format,
                preview,
                parameters,
                interim,
                studentInfo.getGradProgram()
        );

        LOG.exiting(CLASSNAME, _m);
        return report;
    }

    private String getCreditsUsedForGrad(final Achievement achievement) {
        final List<AchievementResult> results = achievement.getResults();
        int totalCredits = 0;

        for (final AchievementResult achievementResult : results) {
            final String credits = nullSafe(achievementResult.getUsedForGrad());
            totalCredits += parseCredits(credits);
        }

        return "" + totalCredits;
    }

    // FIXME: Pass in GraduationProgramCode enum
    private GraduationData adaptGraduationData(
            final StudentInfo studentInfo,
            final Achievement achievement) {
        final String _m = "adaptGraduationData(StudentInfo, Achievement, String)";
        final Object[] params = {studentInfo, achievement};
        LOG.entering(CLASSNAME, _m, params);

        final GraduationData graduationData = new GraduationDataImpl();

        Date gradDate = studentInfo.getGradDate();

        ((GraduationDataImpl) graduationData).setGraduationDate(gradDate);
        ((GraduationDataImpl) graduationData).setHonorsFlag(studentInfo.isHonourFlag());
        ((GraduationDataImpl) graduationData).setDogwoodFlag(studentInfo.isDogwoodFlag());
        ((GraduationDataImpl) graduationData).setProgramNames(studentInfo.getAcademicProgram());
        final String creditsUsedForGrad = getCreditsUsedForGrad(achievement);
        ((GraduationDataImpl) graduationData).setTotalCreditsUsedForGrad(creditsUsedForGrad);

        LOG.exiting(CLASSNAME, _m);

        return graduationData;
    }

    @Override
    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public StudentAchievementReport buildAchievementReport(final ReportFormat format, final boolean interim) throws DomainServiceException, IOException, DataException {
        return createAchievementReport(format, true, interim);
    }

    /**
     * The number of credits can be a pure numeric value or adorned with extra
     * characters (e.g., 2, 2p, (4)). This parses the numeric value regardless
     * of whether there are non-numeric characters present.
     *
     * @param credits The number of credits to parse.
     * @return The parsed value, or 0 if there were no digits present.
     */
    private int parseCredits(final String credits) {
        final String _m = "parseCredits(String)";
        LOG.entering(CLASSNAME, _m);

        // Strip out any non-digits.
        final String numericCredits = credits.replaceAll("[^\\d.]", "");
        int result = 0;

        try {
            if (!numericCredits.isEmpty()) {
                result = parseInt(numericCredits);
            }
        } catch (final Exception ex) {
            LOG.log(Level.WARNING, "Could not parse credits: " + credits, ex);
        }

        LOG.exiting(CLASSNAME, _m);
        return result;

    }

    /**
     * @param results
     * @param code
     * @inheritDoc
     */
    @RolesAllowed({USER, FULFILLMENT_SERVICES_USER})
    @Override
    public List<AchievementResult> sort(
            final List<AchievementResult> results,
            final GraduationProgramCode code) {

        // Perform multiple stable sorts over the achievement results.
        final Comparator<AchievementResult> comparator = createComparator(code);
        Collections.sort(results, comparator);

        // Sort the ungraded courses to the end of the list, which will then
        // be pushed up using the assessment comparator.
        final Comparator<AchievementResult> ungraded = createUngradedComparator();
        Collections.sort(results, ungraded);

        // Sort the ReportCourseType.ASSESSMENT values to the end of the
        // list. This could use a comparator chain.
        final Comparator<AchievementResult> assessments = createAssessmentComparator();
        Collections.sort(results, assessments);

        return results;
    }

    /**
     * The sort order for the courses is as follows:
     * <p>
     * For the 1986 and Adult achievement, the courses are sorted only by course
     * code. For the 2004, 1995, and SCCP achievement, the courses are sorted by
     * course level and then by course name.
     *
     * @param code Program code that influences sort order.
     */
    private Comparator<AchievementResult> createComparator(
            final GraduationProgramCode code) {
        final Comparator<AchievementResult> result;

        switch (code) {
            case PROGRAM_1950:
            case PROGRAM_1986:
                result = createAdultComparator();
                break;

            // 1995, 2004, 2018, etc.
            default:
                result = createRegularComparator();
                break;
        }

        return result;
    }

    /**
     * Returns a comparator that can sort by course code.
     *
     * @return A comparator for sorting by course code.
     */
    private Comparator<AchievementResult> createAdultComparator() {
        return new Comparator<AchievementResult>() {
            @Override
            public int compare(
                    final AchievementResult tr1,
                    final AchievementResult tr2) {
                final String reportCourseType1 = getReportCourseType(tr1);
                final String reportCourseType2 = getReportCourseType(tr2);
                final String code1 = getCourseCode(tr1);
                final String code2 = getCourseCode(tr2);

                return new CompareToBuilder()
                        .append(reportCourseType1, reportCourseType2)
                        .append(code1, code2)
                        .toComparison();
            }
        };
    }

    /**
     * Called for non-Adult reports to provide comparators that can perform
     * stable sub-sorts on the achievement results.
     *
     * @return A list of stable comparators that should be executed in order to
     * sort the achievement results.
     */
    private Comparator<AchievementResult> createRegularComparator() {
        return new Comparator<AchievementResult>() {
            @Override
            public int compare(final AchievementResult tr1, final AchievementResult tr2) {
                final int level1 = getCourseLevel(tr1);
                final int level2 = getCourseLevel(tr2);
                final String name1 = getCourseName(tr1);
                final String name2 = getCourseName(tr2);

                return new CompareToBuilder()
                        .append(level1, level2)
                        .append(name1, name2)
                        .toComparison();
            }
        };
    }

    /**
     * Sorts ungraded to the bottom of the list of achievement results.
     *
     * @return A comparator that can sort ungraded results.
     */
    private Comparator<AchievementResult> createUngradedComparator() {
        return new Comparator<AchievementResult>() {
            @Override
            public int compare(final AchievementResult tr1, final AchievementResult tr2) {
                final int level1 = getCourseLevel(tr1);
                final int level2 = getCourseLevel(tr2);

                final int comparison = new CompareToBuilder()
                        .append(level1, level2)
                        .toComparison();

                return SORT_UNGRADED.equals("" + level1)
                        || SORT_UNGRADED.equals("" + level2)
                        ? comparison
                        : 0;

            }
        };
    }

    /**
     * Used to sort assessments to the bottom of the list of achievement results.
     *
     * @return A comparator that can sort assessment results.
     */
    private Comparator<AchievementResult> createAssessmentComparator() {
        return new Comparator<AchievementResult>() {
            @Override
            public int compare(final AchievementResult tr1, final AchievementResult tr2) {
                final int level1 = getCourseLevel(tr1);
                final int level2 = getCourseLevel(tr2);

                final String reportCourseType1 = getReportCourseType(tr1);
                final String reportCourseType2 = getReportCourseType(tr2);

                final String courseCode1 = getCourseCode(tr1);
                final String courseCode2 = getCourseCode(tr2);

                final int comparison = new CompareToBuilder()
                        .append(level1, level2)
                        .append(reportCourseType1, reportCourseType2)
                        .append(courseCode1, courseCode2)
                        .toComparison();

                return ASSESSMENT.isCode(reportCourseType1)
                        || ASSESSMENT.isCode(reportCourseType2)
                        ? comparison
                        : 0;
            }
        };
    }

    /**
     * Convenience method to obtain a sortable course type.
     *
     * @param tr The achievement result containing report course type that
     *           control sort order.
     * @return The report course type for the given achievement result.
     */
    private String getReportCourseType(final AchievementResult tr) {
        final Course c = tr.getCourse();
        final String reportCourseType = c == null
                ? PROVINCIALLY_EXAMINABLE.getCode()
                : c.getType();

        return reportCourseType;
    }

    /**
     * Convenience method to obtain a sortable course level.
     *
     * @param tr The achievement result containing course levels to be sorted.
     * @return The course level or "99" if the course has no level (and should
     * therefore be sorted to the bottom).
     */
    private int getCourseLevel(final AchievementResult tr) {
        final Course c = tr.getCourse();
        final String cl = c == null ? "" : c.getLevel().trim();
        final String type = c == null ? "" : c.getType();

        final String level = ASSESSMENT.isCode(type)
                ? SORT_ASSESSMENT
                : SORT_UNGRADED;
        final String courseLevel = cl.isEmpty() ? level : cl;
        int result = 0;

        try {
            // Parse "12A" to 12, "11F" to 11, "10" to 10, for sort purposes.
            final NumberFormat nf = getIntegerInstance();
            result = nf.parse(courseLevel).intValue();
        } catch (final Exception ex) {
            LOG.log(Level.SEVERE,
                    "Could not parse course level into integer: " + courseLevel,
                    ex);
        }

        return result;
    }

    /**
     * Convenience method to obtain a sortable course name.
     *
     * @param tr The achievement result containing course names to be sorted.
     * @return The course name, never null, possibly empty.
     */
    private String getCourseName(final AchievementResult tr) {
        final Course c = tr.getCourse();
        final String name = c == null ? "" : c.getName();

        return nullSafe(name);
    }

    /**
     * Convenience method to obtain a sortable course name.
     *
     * @param tr The achievement result containing course names to be sorted.
     * @return The course name, never null, possibly empty.
     */
    private String getCourseCode(final AchievementResult tr) {
        final Course c = tr.getCourse();
        final String code = c == null ? "" : c.getCode();

        return nullSafe(code);
    }

    private InputStream openImageResource(final String resource) throws IOException {
        //final URL url = getReportResource(resource);
        URL url = this.getClass().getResource(DIR_IMAGE_BASE + resource);
        return url.openStream();
    }
}
