/*
 * *********************************************************************
 *  Copyright (c) 2017, Ministry of Education, BC.
 *
 *  All rights reserved.
 *    This information contained herein may not be used in whole
 *    or in part without the express written consent of the
 *    Government of British Columbia, Canada.
 *
 *  Revision Control Information
 *  File:                $Id::                                                 $
 *  Date of Last Commit: $Date::                                               $
 *  Revision Number:     $Rev::                                                $
 *  Last Commit by:      $Author::                                             $
 *
 * ***********************************************************************
 */
package ca.bc.gov.educ.grad.report.service.impl;

import ca.bc.gov.educ.grad.report.dao.GradDataConvertionBean;
import ca.bc.gov.educ.grad.report.dao.ReportRequestDataThreadLocal;
import ca.bc.gov.educ.grad.report.dto.ReportData;
import ca.bc.gov.educ.grad.report.dto.SignatureBlockTypeCode;
import ca.bc.gov.educ.grad.report.dto.impl.*;
import ca.bc.gov.educ.grad.report.exception.EntityNotFoundException;
import ca.bc.gov.educ.grad.report.model.achievement.*;
import ca.bc.gov.educ.grad.report.model.assessment.Assessment;
import ca.bc.gov.educ.grad.report.model.assessment.AssessmentResult;
import ca.bc.gov.educ.grad.report.model.codes.SignatureBlockType;
import ca.bc.gov.educ.grad.report.model.common.DataException;
import ca.bc.gov.educ.grad.report.model.common.DomainServiceException;
import ca.bc.gov.educ.grad.report.model.graduation.GradProgram;
import ca.bc.gov.educ.grad.report.model.graduation.GraduationProgramCode;
import ca.bc.gov.educ.grad.report.model.graduation.NonGradReason;
import ca.bc.gov.educ.grad.report.model.reports.*;
import ca.bc.gov.educ.grad.report.model.school.School;
import ca.bc.gov.educ.grad.report.model.student.PersonalEducationNumber;
import ca.bc.gov.educ.grad.report.model.student.Student;
import ca.bc.gov.educ.grad.report.model.student.StudentInfo;
import ca.bc.gov.educ.grad.report.model.transcript.Course;
import ca.bc.gov.educ.grad.report.model.transcript.GraduationData;
import ca.bc.gov.educ.grad.report.service.GradReportCodeService;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang3.builder.CompareToBuilder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.AsyncResult;
import org.springframework.stereotype.Service;

import javax.annotation.security.DeclareRoles;
import javax.annotation.security.RolesAllowed;
import java.io.IOException;
import java.io.Serializable;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;

import static ca.bc.gov.educ.grad.report.dto.impl.RequirementNames.getName;
import static ca.bc.gov.educ.grad.report.dto.impl.constants.Roles.STUDENT_ACHIEVEMENT_REPORT;
import static ca.bc.gov.educ.grad.report.model.common.support.VerifyUtils.nullSafe;
import static ca.bc.gov.educ.grad.report.model.common.support.impl.Roles.FULFILLMENT_SERVICES_USER;
import static ca.bc.gov.educ.grad.report.model.common.support.impl.Roles.USER;
import static ca.bc.gov.educ.grad.report.model.course.ReportCourseType.ASSESSMENT;
import static ca.bc.gov.educ.grad.report.model.course.ReportCourseType.PROVINCIALLY_EXAMINABLE;
import static ca.bc.gov.educ.grad.report.model.reports.ReportFormat.PDF;
import static java.lang.Integer.parseInt;
import static java.text.NumberFormat.getIntegerInstance;
import static org.apache.commons.lang3.ArrayUtils.isEmpty;

/**
 * The achievement service is an implementation component of the broader
 * Achievement Services group. As part of the mid-tier service layer the
 * buildReport method called by the GUI (browser) to display the unofficial
 * achievement of grades. The display is a rendered report generated by the
 * report service populated with data from the TRAX adaptor for the current user
 * as determined by the student demographics service.
 * <p>
 * This service integrates with the Student Demographics, the TRAX adaptor, and
 * the Reporting Service.
 * </p>
 *
 * The security roles required to build a achievement report are:
 * <ol>
 * <li>XS_REPORT</li>
 * <li>TRAX_READ</li>
 * <li>SXR_READ</li>
 * <li>SXR_SEARCH</li>
 * <li>USER_REPORTS_EXPORT</li>
 * <li>USER_REPORTS_TRANSCRIPT</li>
 * <li>USER_PROFILE_SEARCH</li>
 * <li>USER_PROFILE_READ</li>
 * <li>USER</li>
 * </ol>
 *
 * @author CGI Information Management Consultants Inc.
 */
@Service
@DeclareRoles({STUDENT_ACHIEVEMENT_REPORT, USER, FULFILLMENT_SERVICES_USER})
public class StudentAchievementServiceImpl implements StudentAchievementService, Serializable {

    private static final long serialVersionUID = 5L;

    private static final String CLASSNAME = StudentAchievementServiceImpl.class.getName();
    private static final Logger LOG = Logger.getLogger(CLASSNAME);

    /**
     * Sort order for ungraded courses (to bottom, above assessments).
     */
    private static final String SORT_UNGRADED = "99";

    /**
     * Sort order for assessments (to bottom, below ungraded).
     */
    private static final String SORT_ASSESSMENT = "100";

    private final String FORMAT_COURSE_CODE = "%-5s";
    private final String FORMAT_COURSE_LEVEL = "%-3s";

    @Autowired
    private ReportService reportService;
    @Autowired
    private GradReportCodeService codeService;

    @Autowired
    GradDataConvertionBean gradDataConvertionBean;

    /**
     * Creates the student's official achievement as a PDF (no other formats are
     * allowed for official achievements).
     *
     * @return A filled achievement report suitable for sending to a PSI.
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    @Override
    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public StudentAchievementReport buildOfficialAchievementReport()
            throws DomainServiceException, IOException, DataException {
        return createAchievementReport(PDF, false, false);
    }

    /**
     * Builds an unofficial achievement report.
     *
     * @param format PDF, HTML, etc.
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    @Override
    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public StudentAchievementReport buildAchievementReport(
            final ReportFormat format)
            throws DomainServiceException, IOException, DataException {
        return buildAchievementReport(format, false);
    }

    /**
     * Builds an unofficial achievement report.
     *
     * @param format PDF, HTML, etc.
     * @param pen student identifier.
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    @Override
    @RolesAllowed({FULFILLMENT_SERVICES_USER})
    public StudentAchievementReport buildAchievementReport(
            final ReportFormat format, final PersonalEducationNumber pen, final Parameters parameters, final boolean interim)
            throws DomainServiceException, IOException, DataException {
        return createAchievementReport(format, true, pen, parameters, interim);
    }

    /**
     * Builds an unofficial achievement report asynchronously. Calls
     * <code>createAchievementReport(ReportFormat, true)</code> and returns the
     * result wrapped in an AsyncResult.
     *
     * @param format PDF, HTML, etc.
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    @Override
    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public Future<StudentAchievementReport> buildAchievementReportAsync(
            final ReportFormat format)
            throws DomainServiceException, IOException, DataException {
        return new AsyncResult<>(createAchievementReport(format, true, false));
    }

    @Override
    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public Achievement getAchievement() throws DomainServiceException {
        final String _m = "getAchievement()";
        LOG.entering(CLASSNAME, _m);

        final String pen = getStudentPENId();
        final Achievement achievement = getAchievement(pen, false);

        LOG.exiting(CLASSNAME, _m);
        return achievement;
    }

    @Override
    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public Achievement getAchievement(
            final String pen,
            final boolean interim) throws DomainServiceException {
        final String _m = "getAchievement(String)";
        LOG.entering(CLASSNAME, _m);

        final Achievement achievementInfo = getAchievementInformation(pen);
        final List<AchievementCourse> achievementCourses = getAchievementCourseList(pen, interim);
        final StudentInfo studentInfo = getStudentInfo(pen);
        final String programCode = studentInfo.getGradProgram();
        final GradProgram program = createGradProgram(programCode);
        final Date reportDate = achievementInfo.getIssueDate();

        final Achievement achievement = adapt(
                program.getCode(),
                achievementCourses,
                reportDate,
                interim
        );

        LOG.exiting(CLASSNAME, _m);
        return achievement;
    }

    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public Assessment getAssessment(
            final String pen) throws DomainServiceException {
        final String _m = "getAssessment(String)";
        LOG.entering(CLASSNAME, _m);

        final Achievement achievementInfo = getAchievementInformation(pen);
        final List<AssessmentResult> assessmentResults = getAssessmentResultList(pen);
        final StudentInfo studentInfo = getStudentInfo(pen);
        final String programCode = studentInfo.getGradProgram();
        final GradProgram program = createGradProgram(programCode);
        final Date reportDate = achievementInfo.getIssueDate();

        final Assessment assessment = adapt(
                assessmentResults,
                reportDate
        );

        LOG.exiting(CLASSNAME, _m);
        return assessment;
    }

    @Override
    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public Achievement getAchievementInformation(final String pen) throws DomainServiceException {
        final String _m = "getAchievementInformation(String)";
        LOG.entering(CLASSNAME, _m);

        final Achievement achievement;

        try {
            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        null,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, _m, dse);
                throw dse;
            }

            achievement = gradDataConvertionBean.getAchievement(reportData);

        } catch (Exception ex) {
            String msg = "Failed to access achievement data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, _m, dex);
            throw dex;
        }

        LOG.exiting(CLASSNAME, _m);
        return achievement;
    }

    private GradProgram createGradProgram(String code) {
        if(StringUtils.trimToNull(code) == null) {
            code = GraduationProgramCode.PROGRAM_2018.getCode();
        }
        return new GradProgramImpl(GraduationProgramCode.valueFrom(code));
    }

    /**
     * Creates a report in a specific format, either official or unofficial,
     * depending on the preview value.
     *
     * @param format
     * @param preview Set to false to create an unofficial achievement
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    private StudentAchievementReport createAchievementReport(
            final ReportFormat format,
            final boolean preview, final boolean interim)
            throws DomainServiceException, IOException, DataException {
        final String _m = "createAchievement(ReportFormat, boolean)";
        LOG.entering(CLASSNAME, _m);

        final PersonalEducationNumber pen = getStudentPEN();
        LOG.log(Level.FINE, "Retrieved studentInfo for pen: {0}.", pen.getValue());

        final StudentAchievementReport report = getStudentAchievementReport(
                pen, format, preview, null, interim
        );
        LOG.exiting(CLASSNAME, _m);
        return report;
    }

    /**
     * Creates a report in a specific format, either official or unofficial,
     * depending on the preview value. Takes the PEN to generate the desired
     * report.
     *
     * @param format
     * @param preview Set to false to create an unofficial achievement
     * @return
     * @throws DomainServiceException
     * @throws IOException
     * @throws DataException
     */
    private StudentAchievementReport createAchievementReport(
            final ReportFormat format,
            final boolean preview, final PersonalEducationNumber pen, final Parameters parameters, final boolean interim)
            throws DomainServiceException, IOException, DataException {
        final String _m = "createAchievement(ReportFormat, boolean)";
        LOG.entering(CLASSNAME, _m);
        LOG.log(Level.FINE, "Retrieved achievement for pen: {0}.", pen.getValue());

        final StudentAchievementReport report = getStudentAchievementReport(pen, format, preview, parameters, interim);
        LOG.log(Level.INFO, "Created StudentAchievementReport for pen: {0}.", pen.getValue());

        LOG.exiting(CLASSNAME, _m);
        return report;
    }

    private String getStudentPENId() throws DomainServiceException {
        final String _m = "getStudentPENId()";
        LOG.entering(CLASSNAME, _m);

        final PersonalEducationNumber pen = getStudentPEN();
        final String result = pen.getValue();

        LOG.exiting(CLASSNAME, _m);
        return result;
    }

    private PersonalEducationNumber getStudentPEN() throws DomainServiceException {
        final String _m = "getStudentPEN()";
        LOG.entering(CLASSNAME, _m);

        ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

        if (reportData == null) {
            EntityNotFoundException dse = new EntityNotFoundException(
                    null,
                    "Report Data not exists for the current report generation");
            LOG.throwing(CLASSNAME, _m, dse);
            throw dse;
        }

        PersonalEducationNumberObject pen = new PersonalEducationNumberObject();
        pen.setPen(reportData.getStudent().getPen().getValue());

        LOG.log(Level.FINE, "Confirmed the user is a student and retrieved the PEN: {0}.", pen);
        LOG.exiting(CLASSNAME, _m);
        return pen;
    }

    /**
     * Read the static student data from TRAX which is needed for the achievement
     * service.
     *
     * @param pen
     *
     * @return
     */
    private StudentInfo getStudentInfo(final String pen) throws DataException, DomainServiceException {
        final String _m = "getStudentInfo(String)";
        LOG.entering(CLASSNAME, _m);

        final StudentInfo studentInfo;

        try {

            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        null,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, _m, dse);
                throw dse;
            }

            StudentInfoImpl student = (StudentInfoImpl) gradDataConvertionBean.getStudentInfo(reportData);
            final HashMap<String, String> reasons = gradDataConvertionBean.getNongradReasons(reportData);
            student.setNonGradReasons(reasons);
            studentInfo = student;

            LOG.log(Level.FINER,
                    "Retrieved student info from TRAX for PEN: {0}", pen);

            if (studentInfo == null) {
                final String msg = "Failed to find achievement results in TRAX for PEN: ".concat(pen);
                final DomainServiceException dse = new DomainServiceException(null, msg);
                LOG.throwing(CLASSNAME, _m, dse);
                throw dse;
            } else {
                LOG.log(Level.FINEST, "Retrieved student from achievement:");
                LOG.log(Level.FINEST, "{0} {1} {2}",
                        new Object[]{studentInfo.getPen(), studentInfo.getFirstName(), studentInfo.getLastName()});
            }

        } catch (Exception ex) {
            String msg = "Failed to access TRAX achievement data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, _m, dex);
            throw dex;
        }

        LOG.log(Level.FINE, "Completed call to TRAX.");
        LOG.exiting(CLASSNAME, _m);
        return studentInfo;
    }

    /**
     * Read the collection of achievement courses from the TRAX Adaptor which is
     * required for the achievement service.
     *
     * @param pen Student identifier.
     *
     * @return
     */
    private List<AchievementCourse> getAchievementCourseList(
            final String pen, final boolean interim)
            throws DataException, DomainServiceException {
        final String m_ = "getAchievementCourseList(String, boolean)";
        LOG.entering(CLASSNAME, m_);

        final List<AchievementCourse> results;

        try {

            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        null,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, m_, dse);
                throw dse;
            }

            results = gradDataConvertionBean.getAchievementCourses(reportData);

            LOG.log(Level.INFO,
                    "Retrieved the collection of exam results from TRAX for PEN: {0} INTERIM: {1}",
                    new Object[]{pen, interim});

            if (results != null && !results.isEmpty()) {
                LOG.log(Level.INFO,
                        "Total courses {0} retrieved  for PEN: {1}",
                        new Object[]{results.size(), pen});
                LOG.log(Level.FINEST, "Retrieved student achievement course results:");
                for (AchievementCourse result : results) {
                    LOG.log(Level.FINEST, "{0} {1}",
                            new Object[]{result.getCourseName(), result.getFinalLetterGrade()});
                }
            }
        } catch (final Exception ex) {
            String msg = "Failed to access TRAX achievement course data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, m_, dex);
            throw dex;
        }

        LOG.log(Level.FINE, "Completed call to TRAX.");
        LOG.exiting(CLASSNAME, m_);
        return results;
    }

    /**
     * Read the collection of achievement courses from the TRAX Adaptor which is
     * required for the achievement service.
     *
     * @param pen Student identifier.
     *
     * @return
     */
    private List<AssessmentResult> getAssessmentResultList(
            final String pen)
            throws DataException, DomainServiceException {
        final String m_ = "getAssessmentList(String, boolean)";
        LOG.entering(CLASSNAME, m_);

        final List<AssessmentResult> results;

        try {
            LOG.log(Level.INFO,
                    "Retrieved the collection of exam results from TRAX for PEN: {0}",
                    new Object[]{pen});

            ReportData reportData = ReportRequestDataThreadLocal.getGenerateReportData();

            if (reportData == null) {
                EntityNotFoundException dse = new EntityNotFoundException(
                        null,
                        "Report Data not exists for the current report generation");
                LOG.throwing(CLASSNAME, m_, dse);
                throw dse;
            }

            List<AssessmentResult> resultsList = gradDataConvertionBean.getAssessmentCourses(reportData);
            results = new ArrayList<>();
            for(AssessmentResult course: resultsList) {
                results.add(course);
            }

            if (results != null && !results.isEmpty()) {
                LOG.log(Level.INFO,
                        "Total courses {0} retrieved  for PEN: {1}",
                        new Object[]{results.size(), pen});
                LOG.log(Level.FINEST, "Retrieved student achievement course results:");
                for (AssessmentResult result : results) {
                    LOG.log(Level.FINEST, "{0} {1}",
                            new Object[]{result.getAssessmentCode(), result.getProficiencyScore()});
                }
            }
        } catch (final Exception ex) {
            String msg = "Failed to access TRAX achievement course data for student with PEN: ".concat(pen);
            final DataException dex = new DataException(null, null, msg, ex);
            LOG.throwing(CLASSNAME, m_, dex);
            throw dex;
        }

        LOG.log(Level.FINE, "Completed call to TRAX.");
        LOG.exiting(CLASSNAME, m_);
        return results;
    }

    /**
     * Adapt the TRAX data from the data value object into a Student object.
     *
     * @param pen
     * @param studentInfo
     */
    private Student adaptStudent(
            final PersonalEducationNumber pen,
            final StudentInfo studentInfo) {

        final String _m = "adaptStudent(PersonalEducationNumber, StudentInfo)";
        final Object[] params = {pen, studentInfo};
        LOG.entering(CLASSNAME, _m, params);

        final StudentImpl student = new StudentImpl();
        student.setPen(pen);
        student.setFirstName(studentInfo.getFirstName());
        student.setMiddleName(studentInfo.getMiddleName());
        student.setLastName(studentInfo.getLastName());
        student.setBirthdate(studentInfo.getBirthdate());
        student.setGrade(studentInfo.getGrade());

        final PostalAddressImpl address = new PostalAddressImpl();
        address.setStreetLine1(studentInfo.getStudentAddress1());
        address.setStreetLine2(studentInfo.getStudentAddress2());
        address.setCity(studentInfo.getStudentCity());
        address.setCode(studentInfo.getStudentPostalCode());
        address.setRegion(studentInfo.getStudentProv());
        address.setCountry(studentInfo.getCountryCode());
        student.setCurrentMailingAddress(address);

        final Map<String, SignatureBlockTypeCode> signatureBlockTypeCodes = codeService.getSignatureBlockTypeCodesMap();
        final Map<String, SignatureBlockType> signatureBlockTypes = new HashMap<>();
        signatureBlockTypes.putAll(signatureBlockTypeCodes);
        student.setSignatureBlockTypes(signatureBlockTypes);

        LOG.exiting(CLASSNAME, _m);
        return student;
    }

    /**
     * Adapt the TRAX data from the data value object into a School object.
     *
     * @param studentInfo
     */
    private School adaptSchool(final StudentInfo studentInfo) {
        final String m_ = "adaptSchool(StudentInfo)";
        LOG.entering(CLASSNAME, m_, studentInfo);

        final SchoolImpl school = new SchoolImpl();
        school.setMincode(studentInfo.getMincode());
        school.setName(studentInfo.getSchoolName());
        school.setTypeIndicator(studentInfo.getSchoolTypeIndicator());
        school.setTypeBanner(studentInfo.getSchoolTypeBanner());

        final CanadianPostalAddressImpl address = new CanadianPostalAddressImpl();
        address.setStreet1(studentInfo.getSchoolStreet());
        address.setStreet2(studentInfo.getSchoolStreet2());
        address.setCity(studentInfo.getSchoolCity());
        address.setPostalCode(studentInfo.getSchoolPostalCode());
        address.setProvince(studentInfo.getSchoolProv());
        school.setAddress(address);

        LOG.exiting(CLASSNAME, m_);
        return school;
    }

    /**
     * Adapt the TRAX data from the collection of data value objects into a
     * Achievement object.
     *
     * @param code The graduation program code that influences sort order.
     * @param achievementCourses
     * @param issueDate
     */
    private Achievement adapt(
            final GraduationProgramCode code,
            final List<AchievementCourse> achievementCourses,
            final Date issueDate,
            final boolean interim) {
        final String m_ = "adapt(GraduationProgramCode, List<AchievementCourse>, Date, boolean)";
        LOG.entering(CLASSNAME, m_, achievementCourses);

        final List<AchievementResult> achievementResults = adapt(
                code, achievementCourses);

        final AchievementImpl achievement = new AchievementImpl();
        achievement.setIssueDate(issueDate);
        achievement.setResults(achievementResults);
        achievement.setInterim(interim);

        LOG.exiting(CLASSNAME, m_);
        return achievement;
    }

    private Assessment adapt(
            final List<AssessmentResult> assessmentResults,
            final Date issueDate) {
        final String m_ = "adapt(GraduationProgramCode, List<AchievementCourse>, Date, boolean)";
        LOG.entering(CLASSNAME, m_, assessmentResults);

        final AssessmentImpl assessment = new AssessmentImpl();
        assessment.setIssueDate(issueDate);
        assessment.setResults(assessmentResults);

        LOG.exiting(CLASSNAME, m_);
        return assessment;
    }

    /**
     * Adapt the TRAX data from the collection of data value objects into a
     * Achievement object.
     *
     * @param programCode The graduation program code that influences sort
     * order.
     * @param achievementCourses
     */
    private List<AchievementResult> adapt(
            final GraduationProgramCode programCode,
            final List<AchievementCourse> achievementCourses) {
        final String m_ = "adapt(GraduationProgramCode, List<AchievementCourse>)";
        LOG.entering(CLASSNAME, m_, achievementCourses);

        List<AchievementResult> achievementResults = Collections.emptyList();

        if (achievementCourses != null) {
            final int size = achievementCourses.size();
            achievementResults = new ArrayList<>(size);

            for (final AchievementCourse achievementCourse : achievementCourses) {
                final String courseType = achievementCourse.getCourseType();

                final String eq = achievementCourse.getEquivalency();
                final String req = achievementCourse.getRequirement();
                final String ufg = achievementCourse.getUsedForGrad();
                final String reqName = getName(req, programCode.toString());
                final AchievementResultImpl tResult = new AchievementResultImpl(
                        req, eq, ufg, reqName);

                final String courseName = achievementCourse.getCourseName();
                final String courseCode = achievementCourse.getCourseCode();
                final String courseLevel = achievementCourse.getCourseLevel();
                final String traxCredits = achievementCourse.getCredits();
                final String relatedCourse = achievementCourse.getRelatedCourse();
                final String relatedLevel = achievementCourse.getRelatedLevel();

                final String sessionDate = achievementCourse.getSessionDate();
                final CourseImpl course = new CourseImpl(
                        courseName, courseCode,
                        courseLevel, traxCredits,
                        sessionDate, courseType,
                        relatedCourse, relatedLevel);

                tResult.setCourse(course);

                final String schoolPct = achievementCourse.getSchoolPercent();
                final String examPct = achievementCourse.getExamPercent();
                String finalPct = achievementCourse.getFinalPercent();
                final String finalLetterGrade = achievementCourse.getFinalLetterGrade();
                final String interimPct = achievementCourse.getInterimMark();
                final String interimLetterGrade = achievementCourse.getInterimLetterGrade();

                final MarkImpl mark = new MarkImpl();
                mark.setSchoolPercent(schoolPct);
                mark.setExamPercent(examPct);

                // Marks should only contain interim OR final
                if ("0".equals(finalPct)) {
                    finalPct = "";
                }

                if (finalPct.isEmpty() && finalLetterGrade.isEmpty()) {
                    mark.setInterimLetterGrade(interimLetterGrade);
                    mark.setInterimPercent(interimPct);
                } else {
                    mark.setFinalLetterGrade(finalLetterGrade);
                    mark.setFinalPercent(finalPct);
                }

                tResult.setMark(mark);
                achievementResults.add(tResult);
            }

            sort(achievementResults, programCode);
        }

        LOG.exiting(CLASSNAME, m_);
        return achievementResults;
    }

    /**
     * Convert non-graduation reasons from a TRAX map to an STs list.
     *
     * @param traxStudent The student instance that has non-grad reasons to
     * convert.
     *
     * @return The map of non-grad reasons converted from a map to a list of
     * NonGradReasons instances.
     */
    private List<NonGradReason> adaptReasons(final StudentInfo traxStudent) {
        final String _m = "adaptReasons(StudentInfo)";
        LOG.entering(CLASSNAME, _m);

        final Map<String, String> traxReasons = traxStudent.getNonGradReasons();
        final List<NonGradReason> reasons = new ArrayList<>();

        for (Map.Entry<String, String> entry : traxReasons.entrySet()) {
            final String key = entry.getKey();
            final String value = entry.getValue();
            NonGradReasonImpl r = new NonGradReasonImpl();
            r.setCode(key);
            r.setDescription(value);
            reasons.add(r);
        }

        LOG.exiting(CLASSNAME, _m);
        return reasons;
    }

    /**
     * Create an unofficial achievement of grades report.
     *
     * @param reportFormat
     * @param preview
     * @param student
     * @param school
     * @param logo
     * @param achievement
     * @param program
     * @param nonGradReasons
     * @param gradMessage
     *
     * @return
     *
     * @throws DomainServiceException
     */
    private synchronized StudentAchievementReport createReport(
            final ReportFormat reportFormat,
            final boolean preview,
            final Student student,
            final School school,
            final String logo,
            final Achievement achievement,
            final Assessment assessment,
            final GradProgram program,
            final List<NonGradReason> nonGradReasons,
            final String gradMessage,
            final Date updateDt,
            final Parameters parameters,
            final GraduationData graduationData) throws DomainServiceException, IOException {
        final String _m = "createReport(...)";
        LOG.entering(CLASSNAME, _m);

        final AchievementReport report = reportService.createAchievementReport();

        if (parameters != null) {
            report.setParameters(parameters);
        }

        // Indicate official/unofficial
        report.setPreview(preview);

        report.setStudent(student);
        report.setSchool(school, logo);
        report.setGraduationProgram(program);
        report.setAchievement(achievement);
        report.setAssessment(assessment);
        report.setGraduationStatus(nonGradReasons, gradMessage);
        report.setReportDate(updateDt);
        report.setFormat(reportFormat);
        report.setGraduationData(graduationData);

        final boolean interim = ((AchievementImpl) achievement).getInterim();
        report.setInterim(interim);

        final ReportDocument document;

        try {
            ca.bc.gov.educ.grad.report.dto.reports.data.impl.Student stu = (ca.bc.gov.educ.grad.report.dto.reports.data.impl.Student)report.getDataSource();

            System.out.println("student.pen = " + stu.getPEN());
            System.out.println("student.firstName = " + stu.getFirstName());
            System.out.println("student.lastName = " + stu.getLastName());
            System.out.println("student.middleNames = " + stu.getMiddleNames());
            System.out.println("student.birthdate = " + new SimpleDateFormat( "yy/MM/dd" ).format(stu.getBirthdate()));
            System.out.println("student.graduationProgram.description = " + stu.getGraduationProgram().getDescription());
            System.out.println("report date = " + new SimpleDateFormat( "d-MMM-yyyy").format( new Date()).toUpperCase());
            System.out.println("student.school.name = " + stu.getSchool().getName().toUpperCase());
            System.out.println("student.school.districtOrganisation.name = " + stu.getSchool().getDistrictOrganisation().getName());
            System.out.println("student.school.districtOrganisation.logoCode = " + stu.getSchool().getDistrictOrganisation().getLogoCode());
            System.out.println("student.school.address.formattedStreet = " + stu.getSchool().getAddress().getFormattedStreet());
            System.out.println("student.school.address.city = " + stu.getSchool().getAddress().getCity() + stu.getSchool().getAddress().getRegion());
            System.out.println("student.school.address.region = " + stu.getSchool().getAddress().getRegion());
            System.out.println("student.school.address.postalCode = " + stu.getSchool().getAddress().getPostalCode());
            System.out.println("student.school.typeBanner = " + stu.getSchool().getTypeBanner().toUpperCase());
            System.out.println("student.school.ministryCode = " + stu.getSchool().getMinistryCode().toUpperCase());
            System.out.println("student.achievementResults = " + stu.getAchievementResults().size());
            System.out.println("student.assessments = " + stu.getAssessments().size());
            System.out.println("student.provinciallyExaminableCourses = " + stu.getProvinciallyExaminableCourses().size());
            System.out.println("student.nonProvinciallyExaminableCourses = " + stu.getNonProvinciallyExaminableCourses().size());
            System.out.println("student.signatureBlockTypes = " + stu.getSignatureBlockTypes().size());
            System.out.println("student.status.graduationMessage = " + stu.getStatus().getGraduationMessage());
            System.out.println("student.status.graduated = " + stu.getStatus().getGraduated());

            document = reportService.export(report);
        } catch (final Exception ex) {
            final String msg = "Failed to create report.";
            LOG.log(Level.SEVERE, msg, ex);
            final DomainServiceException dse = new DomainServiceException(msg, ex);
            LOG.throwing(CLASSNAME, _m, dse);
            throw dse;
        }
        LOG.log(Level.FINE, "Created document {0} for student {1}.", new Object[]{document, student.getPen()});

        final String filename = report.getFilename();
        final byte[] content = document.asBytes();

        if (isEmpty(content)) {
            final String msg = "The generated report output is empty.";
            DomainServiceException dse = new DomainServiceException(msg);
            LOG.throwing(CLASSNAME, _m, dse);
            throw dse;
        }

        final StudentAchievementReport achievementReport = new StudentAchievementReportImpl(
                content, reportFormat, filename, "Achievement"
        );
        LOG.log(Level.FINE, "Created StudentAchievementReport {0} for student {1}.", new Object[]{achievementReport, student.getPen()});

        LOG.exiting(CLASSNAME, _m);
        return achievementReport;
    }

    @Override
    @RolesAllowed({FULFILLMENT_SERVICES_USER})
    public Parameters createParameters() {
        final String _m = "createParameters()";
        LOG.entering(CLASSNAME, _m);

        Parameters parameters = reportService.createParameters();

        LOG.exiting(CLASSNAME, _m);
        return parameters;
    }

    private StudentAchievementReport getStudentAchievementReport(
            final PersonalEducationNumber personalEducationNumber,
            final ReportFormat format,
            final boolean preview,
            final Parameters parameters,
            final boolean interim) throws DomainServiceException, IOException {
        final String _m = "getStudentAchievementReport(String, ReportFormat, boolean, Parameters, boolean)";
        LOG.entering(CLASSNAME, _m);
        final String pen = personalEducationNumber.getValue();
        final StudentInfo studentInfo = getStudentInfo(pen);

        // Adapt TRAX data to other objects for reporting.
        final String programCode = studentInfo.getGradProgram();
        final String logo = studentInfo.getLogo();
        final Achievement achievement = getAchievement(pen, interim);
        final Assessment assessment = getAssessment(pen);

        final Student student = adaptStudent(personalEducationNumber, studentInfo);
        final School school = adaptSchool(studentInfo);

        // FIXME: Replace with GraduationProgramCode enum.
        final GradProgram program = createGradProgram(programCode);
        final GraduationData graduationData = adaptGraduationData(studentInfo, achievement);

        final String gradMessage = studentInfo.getGradMessage();
        final List<NonGradReason> nonGradReasons = adaptReasons(studentInfo);

        final StudentAchievementReport report = createReport(
                format,
                preview,
                student,
                school,
                logo,
                achievement,
                assessment,
                program,
                nonGradReasons,
                gradMessage,
                achievement.getIssueDate(),
                parameters,
                graduationData
        );

        LOG.exiting(CLASSNAME, _m);
        return report;
    }

    private String getCreditsUsedForGrad(final Achievement achievement) {
        final List<AchievementResult> results = achievement.getResults();
        int totalCredits = 0;

        for (final AchievementResult achievementResult : results) {
            final String credits = nullSafe(achievementResult.getUsedForGrad());
            totalCredits += parseCredits(credits);
        }

        return "" + totalCredits;
    }

    // FIXME: Pass in GraduationProgramCode enum
    private GraduationData adaptGraduationData(
            final StudentInfo studentInfo,
            final Achievement achievement) {
        final String _m = "adaptGraduationData(StudentInfo, Achievement, String)";
        final Object[] params = {studentInfo, achievement};
        LOG.entering(CLASSNAME, _m, params);

        final GraduationData graduationData = new GraduationDataImpl();

        Date gradDate = studentInfo.getGradDate();

        ((GraduationDataImpl) graduationData).setGraduationDate(gradDate);
        ((GraduationDataImpl) graduationData).setHonorsFlag(studentInfo.isHonourFlag());
        ((GraduationDataImpl) graduationData).setDogwoodFlag(studentInfo.isDogwoodFlag());
        ((GraduationDataImpl) graduationData).setProgramNames(studentInfo.getAcademicProgram());
        final String creditsUsedForGrad = getCreditsUsedForGrad(achievement);
        ((GraduationDataImpl) graduationData).setTotalCreditsUsedForGrad(creditsUsedForGrad);

        LOG.exiting(CLASSNAME, _m);

        return graduationData;
    }

    @Override
    @RolesAllowed({STUDENT_ACHIEVEMENT_REPORT, USER})
    public StudentAchievementReport buildAchievementReport(final ReportFormat format, final boolean interim) throws DomainServiceException, IOException, DataException {
        return createAchievementReport(format, true, interim);
    }

    /**
     * Ensure that the student's highest mark for a particular course is used.
     * This will remove any duplicate courses that may be present in favour of
     * the highest marked course.
     *
     * @param results Courses for PEN user which might have duplicated courses
     * @return
     */
    private List<AchievementCourse> filterCourses(final List<AchievementCourse> results) {

        final List<AchievementCourse> resultOfCourses = new ArrayList<>();
        for (final AchievementCourse course : results) {

            if (!resultOfCourses.contains(course)) {
                final AchievementCourse interimCourse
                        = getInterimCourse(course, results);

                if (!(resultOfCourses.contains(interimCourse))) {
                    resultOfCourses.add(interimCourse);
                }
            }
        }

        return resultOfCourses;
    }

    /**
     * If the in progress course is a duplicate of a successfully complete
     * course (i.e. the course already appears on the student's achievement with
     * a passing final mark), the in progress course replaces the successfully
     * completed occurrence of the course if and only if the interim percent is
     * greater than the final percent on the successfully completed occurrence
     * of the course. If the interim percent is blank it should not replace the
     * successfully completed occurrence of the course.
     */
    private AchievementCourse getInterimCourse(
            AchievementCourse course,
            final List<AchievementCourse> results) {
        //Check for dulicate courses
        for (final AchievementCourse compareCourse : results) {
            //Check and compare two courses for duplication and if required
            //replace course based on requirement.
            if (course.courseEquals(compareCourse)
                    && course.compareCourse(compareCourse)) {
                course = compareCourse;
            }
        }
        return course;

    }

    /**
     * The number of credits can be a pure numeric value or adorned with extra
     * characters (e.g., 2, 2p, (4)). This parses the numeric value regardless
     * of whether there are non-numeric characters present.
     *
     * @param credits The number of credits to parse.
     * @return The parsed value, or 0 if there were no digits present.
     */
    private int parseCredits(final String credits) {
        final String _m = "parseCredits(String)";
        LOG.entering(CLASSNAME, _m);

        // Strip out any non-digits.
        final String numericCredits = credits.replaceAll("[^\\d.]", "");
        int result = 0;

        try {
            if (!numericCredits.isEmpty()) {
                result = parseInt(numericCredits);
            }
        } catch (final Exception ex) {
            LOG.log(Level.WARNING, "Could not parse credits: " + credits, ex);
        }

        LOG.exiting(CLASSNAME, _m);
        return result;

    }

    /**
     * @param results
     * @param code
     * @inheritDoc
     */
    @RolesAllowed({USER, FULFILLMENT_SERVICES_USER})
    @Override
    public List<AchievementResult> sort(
            final List<AchievementResult> results,
            final GraduationProgramCode code) {

        // Perform multiple stable sorts over the achievement results.
        final Comparator<AchievementResult> comparator = createComparator(code);
        Collections.sort(results, comparator);

        // Sort the ungraded courses to the end of the list, which will then
        // be pushed up using the assessment comparator.
        final Comparator<AchievementResult> ungraded = createUngradedComparator();
        Collections.sort(results, ungraded);

        // Sort the ReportCourseType.ASSESSMENT values to the end of the
        // list. This could use a comparator chain.
        final Comparator<AchievementResult> assessments = createAssessmentComparator();
        Collections.sort(results, assessments);

        return results;
    }

    /**
     * The sort order for the courses is as follows:
     *
     * For the 1986 and Adult achievement, the courses are sorted only by course
     * code. For the 2004, 1995, and SCCP achievement, the courses are sorted by
     * course level and then by course name.
     *
     * @param code Program code that influences sort order.
     */
    private Comparator<AchievementResult> createComparator(
            final GraduationProgramCode code) {
        final Comparator<AchievementResult> result;

        switch (code) {
            case PROGRAM_1950:
            case PROGRAM_1986:
                result = createAdultComparator();
                break;

            // 1995, 2004, 2018, etc.
            default:
                result = createRegularComparator();
                break;
        }

        return result;
    }

    /**
     * Returns a comparator that can sort by course code.
     *
     * @return A comparator for sorting by course code.
     */
    private Comparator<AchievementResult> createAdultComparator() {
        return new Comparator<AchievementResult>() {
            @Override
            public int compare(
                    final AchievementResult tr1,
                    final AchievementResult tr2) {
                final String reportCourseType1 = getReportCourseType(tr1);
                final String reportCourseType2 = getReportCourseType(tr2);
                final String code1 = getCourseCode(tr1);
                final String code2 = getCourseCode(tr2);

                return new CompareToBuilder()
                        .append(reportCourseType1, reportCourseType2)
                        .append(code1, code2)
                        .toComparison();
            }
        };
    }

    /**
     * Called for non-Adult reports to provide comparators that can perform
     * stable sub-sorts on the achievement results.
     *
     * @return A list of stable comparators that should be executed in order to
     * sort the achievement results.
     */
    private Comparator<AchievementResult> createRegularComparator() {
        return new Comparator<AchievementResult>() {
            @Override
            public int compare(final AchievementResult tr1, final AchievementResult tr2) {
                final int level1 = getCourseLevel(tr1);
                final int level2 = getCourseLevel(tr2);
                final String name1 = getCourseName(tr1);
                final String name2 = getCourseName(tr2);

                return new CompareToBuilder()
                        .append(level1, level2)
                        .append(name1, name2)
                        .toComparison();
            }
        };
    }

    /**
     * Sorts ungraded to the bottom of the list of achievement results.
     *
     * @return A comparator that can sort ungraded results.
     */
    private Comparator<AchievementResult> createUngradedComparator() {
        return new Comparator<AchievementResult>() {
            @Override
            public int compare(final AchievementResult tr1, final AchievementResult tr2) {
                final int level1 = getCourseLevel(tr1);
                final int level2 = getCourseLevel(tr2);

                final int comparison = new CompareToBuilder()
                        .append(level1, level2)
                        .toComparison();

                return SORT_UNGRADED.equals("" + level1)
                        || SORT_UNGRADED.equals("" + level2)
                                ? comparison
                                : 0;

            }
        };
    }

    /**
     * Used to sort assessments to the bottom of the list of achievement results.
     *
     * @return A comparator that can sort assessment results.
     */
    private Comparator<AchievementResult> createAssessmentComparator() {
        return new Comparator<AchievementResult>() {
            @Override
            public int compare(final AchievementResult tr1, final AchievementResult tr2) {
                final int level1 = getCourseLevel(tr1);
                final int level2 = getCourseLevel(tr2);

                final String reportCourseType1 = getReportCourseType(tr1);
                final String reportCourseType2 = getReportCourseType(tr2);

                final String courseCode1 = getCourseCode(tr1);
                final String courseCode2 = getCourseCode(tr2);

                final int comparison = new CompareToBuilder()
                        .append(level1, level2)
                        .append(reportCourseType1, reportCourseType2)
                        .append(courseCode1, courseCode2)
                        .toComparison();

                return ASSESSMENT.isCode(reportCourseType1)
                        || ASSESSMENT.isCode(reportCourseType2)
                                ? comparison
                                : 0;
            }
        };
    }

    /**
     * Convenience method to obtain a sortable course type.
     *
     * @param tr The achievement result containing report course type that
     * control sort order.
     * @return The report course type for the given achievement result.
     */
    private String getReportCourseType(final AchievementResult tr) {
        final Course c = tr.getCourse();
        final String reportCourseType = c == null
                ? PROVINCIALLY_EXAMINABLE.getCode()
                : c.getType();

        return reportCourseType;
    }

    /**
     * Convenience method to obtain a sortable course level.
     *
     * @param tr The achievement result containing course levels to be sorted.
     * @return The course level or "99" if the course has no level (and should
     * therefore be sorted to the bottom).
     */
    private int getCourseLevel(final AchievementResult tr) {
        final Course c = tr.getCourse();
        final String cl = c == null ? "" : c.getLevel().trim();
        final String type = c == null ? "" : c.getType();

        final String level = ASSESSMENT.isCode(type)
                ? SORT_ASSESSMENT
                : SORT_UNGRADED;
        final String courseLevel = cl.isEmpty() ? level : cl;
        int result = 0;

        try {
            // Parse "12A" to 12, "11F" to 11, "10" to 10, for sort purposes.
            final NumberFormat nf = getIntegerInstance();
            result = nf.parse(courseLevel).intValue();
        } catch (final Exception ex) {
            LOG.log(Level.SEVERE,
                    "Could not parse course level into integer: " + courseLevel,
                    ex);
        }

        return result;
    }

    /**
     * Convenience method to obtain a sortable course name.
     *
     * @param tr The achievement result containing course names to be sorted.
     * @return The course name, never null, possibly empty.
     */
    private String getCourseName(final AchievementResult tr) {
        final Course c = tr.getCourse();
        final String name = c == null ? "" : c.getName();

        return nullSafe(name);
    }

    /**
     * Convenience method to obtain a sortable course name.
     *
     * @param tr The achievement result containing course names to be sorted.
     * @return The course name, never null, possibly empty.
     */
    private String getCourseCode(final AchievementResult tr) {
        final Course c = tr.getCourse();
        final String code = c == null ? "" : c.getCode();

        return nullSafe(code);
    }
}
