package ca.bc.gov.educ.grad.report.api.util;

public interface PermissionsContants {
	String _PREFIX = "#oauth2.hasAnyScope('";
	String _SUFFIX = "')";

	String STUDENT_ACHIEVEMENT_REPORT = _PREFIX + "CREATE_STUDENT_ACHIEVEMENT_REPORT" + _SUFFIX;
	String STUDENT_TRANSCRIPT_REPORT = _PREFIX + "CREATE_STUDENT_TRANSCRIPT_REPORT" + _SUFFIX;
	String STUDENT_XML_TRANSCRIPT_REPORT = _PREFIX + "CREATE_STUDENT_XML_TRANSCRIPT_REPORT" + _SUFFIX;
	String STUDENT_CERTIFICATE = _PREFIX + "CREATE_STUDENT_CERTIFICATE" + _SUFFIX;
	String PACKING_SLIP= _PREFIX + "CREATE_PACKING_SLIP" + _SUFFIX;
    String SCHOOL_DISTRIBUTION = _PREFIX + "CREATE_SCHOOL_DISTRIBUTION" + _SUFFIX;

	String CREATE_OR_UPDATE_SIGNATURE_IMAGE = _PREFIX + "CREATE_OR_UPDATE_SIGNATURE_IMAGE" + _SUFFIX;
	String READ_SIGNATURE_IMAGE_BY_CODE = _PREFIX + "READ_SIGNATURE_IMAGE_BY_CODE" + _SUFFIX;
	String CREATE_OR_UPDATE_SIGNATURE_BLOCK_TYPE_CODE = _PREFIX + "CREATE_OR_UPDATE_SIGNATURE_BLOCK_TYPE_CODE" + _SUFFIX;
	String READ_SIGNATURE_BLOCK_TYPE_CODE = _PREFIX + "READ_SIGNATURE_BLOCK_TYPE_CODE" + _SUFFIX;
}
