package ca.bc.gov.educ.grad.report.api.util;

public interface PermissionsContants {
	String _PREFIX = "hasAuthority('";
	String _SUFFIX = "')";

	String STUDENT_ACHIEVEMENT_REPORT = _PREFIX + "SCOPE_CREATE_STUDENT_ACHIEVEMENT_REPORT" + _SUFFIX;
	String STUDENT_TRANSCRIPT_REPORT = _PREFIX + "SCOPE_CREATE_STUDENT_TRANSCRIPT_REPORT" + _SUFFIX;
	String STUDENT_XML_TRANSCRIPT_REPORT = _PREFIX + "SCOPE_CREATE_STUDENT_XML_TRANSCRIPT_REPORT" + _SUFFIX;
	String STUDENT_CERTIFICATE = _PREFIX + "SCOPE_CREATE_STUDENT_CERTIFICATE" + _SUFFIX;
	String PACKING_SLIP= _PREFIX + "SCOPE_CREATE_PACKING_SLIP" + _SUFFIX;
    String SCHOOL_DISTRIBUTION = _PREFIX + "SCOPE_CREATE_SCHOOL_DISTRIBUTION" + _SUFFIX;
	String SCHOOL_GRADUATION = _PREFIX + "SCOPE_CREATE_SCHOOL_GRADUATION" + _SUFFIX;
	String SCHOOL_NON_GRADUATION = _PREFIX + "SCOPE_CREATE_SCHOOL_NON_GRADUATION" + _SUFFIX;
    String STUDENT_NON_GRAD = _PREFIX + "SCOPE_CREATE_STUDENT_NON_GRAD" + _SUFFIX;

	String CREATE_OR_UPDATE_SIGNATURE_IMAGE = _PREFIX + "SCOPE_CREATE_OR_UPDATE_SIGNATURE_IMAGE" + _SUFFIX;
	String READ_SIGNATURE_IMAGE_BY_CODE = _PREFIX + "SCOPE_READ_SIGNATURE_IMAGE_BY_CODE" + _SUFFIX;
	String CREATE_OR_UPDATE_SIGNATURE_BLOCK_TYPE_CODE = _PREFIX + "SCOPE_CREATE_OR_UPDATE_SIGNATURE_BLOCK_TYPE_CODE" + _SUFFIX;
	String READ_SIGNATURE_BLOCK_TYPE_CODE = _PREFIX + "SCOPE_READ_SIGNATURE_BLOCK_TYPE_CODE" + _SUFFIX;
}
