--------------------------------------------------------
--  File created - Wednesday-August-04-2021
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GRAD_REPORT_SIGNATURE
--------------------------------------------------------

ALTER TABLE GRAD_REPORT_SIGNATURE ADD DISTNO VARCHAR2(3) NULL;
ALTER TABLE GRAD_REPORT_SIGNATURE ADD DIST_NAME VARCHAR2(64) NULL;

ALTER TABLE GRAD_REPORT_SIGNATURE MODIFY (CREATE_USER INVISIBLE);
ALTER TABLE GRAD_REPORT_SIGNATURE MODIFY (CREATE_DATE INVISIBLE);
ALTER TABLE GRAD_REPORT_SIGNATURE MODIFY (UPDATE_USER INVISIBLE);
ALTER TABLE GRAD_REPORT_SIGNATURE MODIFY (UPDATE_DATE INVISIBLE);

ALTER TABLE GRAD_REPORT_SIGNATURE MODIFY (CREATE_USER VISIBLE);
ALTER TABLE GRAD_REPORT_SIGNATURE MODIFY (CREATE_DATE VISIBLE);
ALTER TABLE GRAD_REPORT_SIGNATURE MODIFY (UPDATE_USER VISIBLE);
ALTER TABLE GRAD_REPORT_SIGNATURE MODIFY (UPDATE_DATE VISIBLE);

