Insert into SCHOOL_FUNDING_GROUP_CODE (SCHOOL_FUNDING_GROUP_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) values (' ','No School',null,null,null,null);
Insert into SCHOOL_FUNDING_GROUP_CODE (SCHOOL_FUNDING_GROUP_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) values ('1',null,null,null,null,null);
Insert into SCHOOL_FUNDING_GROUP_CODE (SCHOOL_FUNDING_GROUP_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) values ('2',null,null,null,null,null);
Insert into SCHOOL_FUNDING_GROUP_CODE (SCHOOL_FUNDING_GROUP_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) values ('3',null,null,null,null,null);
Insert into SCHOOL_FUNDING_GROUP_CODE (SCHOOL_FUNDING_GROUP_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) values ('4',null,null,null,null,null);
Insert into SCHOOL_FUNDING_GROUP_CODE (SCHOOL_FUNDING_GROUP_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) values ('5',null,null,null,null,null);
Insert into SCHOOL_FUNDING_GROUP_CODE (SCHOOL_FUNDING_GROUP_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE) values ('6',null,null,null,null,null);
COMMIT;